// Port of services/rendering/policy/typography_policy.py — the body-pipeline
// (C3-N3) typography constants. Values mirror the Python module verbatim.

// Body font growth for translated paragraphs that visually underfill their OCR
// bbox. These values define the font-size side of the vertical slack budget.
pub const BODY_UNDERFILLED_DENSITY_FLOOR_TRIGGER: f64 = 0.60;
pub const BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET: f64 = 0.80;
pub const BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET_NO_SOURCE: f64 = 0.68;
pub const BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET_SHORT: f64 = 0.72;
pub const BODY_UNDERFILLED_DENSITY_SAFE_MAX: f64 = 0.98;
pub const BODY_UNDERFILLED_RECOVERY_MAX_ITERATIONS: i32 = 6;
pub const BODY_UNDERFILLED_RECOVERY_FONT_STEP_PT: f64 = 0.28;
pub const BODY_UNDERFILLED_RECOVERY_LEADING_STEP_EM: f64 = 0.06;
pub const BODY_UNDERFILLED_UNIFIED_FONT_MAX_STEP_PT: f64 = 0.0;
pub const BODY_UNDERFILLED_FONT_GROW_DENSITY_TRIGGER: f64 = BODY_UNDERFILLED_DENSITY_FLOOR_TRIGGER;
pub const BODY_UNDERFILLED_FONT_GROW_DENSITY_LIMIT: f64 = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET;
pub const BODY_UNDERFILLED_FONT_GROW_MAX_PT: f64 = 1.15;
pub const BODY_UNDERFILLED_FONT_GROW_CONTEXT_BONUS_PT: f64 = 0.18;
pub const BODY_UNDERFILLED_FONT_GROW_PAGE_BONUS_PT: f64 = 0.16;
pub const BODY_UNDERFILLED_FONT_GROW_EXP_RATE: f64 = 1.55;
pub const BODY_UNDERFILLED_FONT_GROW_MAX_LINES: i32 = 8;
pub const BODY_UNDERFILLED_FONT_GROW_SHORT_LINE_BONUS: f64 = 0.04;
pub const BODY_UNDERFILLED_FONT_GROW_TALL_SLACK_BONUS: f64 = 0.08;
pub const BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_BONUS_PT: f64 = 0.18;
pub const BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_CAP_BONUS_PT: f64 = 0.16;
pub const BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_DENSITY_BONUS: f64 = 0.01;
pub const BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_RATIO_OFFSET: f64 = 1.25;
pub const BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_RATIO_RANGE: f64 = 2.75;
pub const BODY_UNDERFILLED_FONT_HARMONIZE_MAX_RATIO: f64 = 1.16;
pub const BODY_UNDERFILLED_FONT_GROW_MIN_LINES: i32 = 2;
pub const BODY_UNDERFILLED_FONT_GROW_MIN_HEIGHT_PT: f64 = 22.0;
pub const BODY_UNDERFILLED_FONT_GROW_SHORT_MAX_PT: f64 = 0.0;
pub const BODY_UNDERFILLED_FONT_GROW_LOW_FONT_SKIP_DELTA_PT: f64 = 0.20;

// Page-level body font anchor. Long, stable body paragraphs act as anchors for
// short body blocks on the same page/column so font size does not jump sharply.
pub const PAGE_BODY_FONT_ANCHOR_COUNT: usize = 2;
pub const PAGE_BODY_FONT_ANCHOR_MIN_HEIGHT_PT: f64 = 42.0;
pub const PAGE_BODY_FONT_ANCHOR_MIN_LINES: i64 = 3;
pub const PAGE_BODY_FONT_ANCHOR_MIN_WIDTH_RATIO: f64 = 0.62;
pub const PAGE_BODY_FONT_ANCHOR_TARGET_MAX_RATIO: f64 = 1.12;
pub const PAGE_BODY_FONT_ANCHOR_TARGET_MAX_DELTA_PT: f64 = 1.15;
pub const PAGE_BODY_FONT_ANCHOR_APPLY_DENSITY_LIMIT: f64 = 1.20;
pub const PAGE_BODY_FONT_ANCHOR_SHORT_HEIGHT_RELAX_RATIO: f64 = 1.72;
pub const PAGE_BODY_FONT_ANCHOR_SHORT_HEIGHT_RELAX_MAX_EXTRA_PT: f64 = 14.0;

// Body font unification. Prefer a conservative low-page anchor: one-line OCR
// boxes have no leading budget, so using large blocks as the target can make
// short/tight text jump upward and mislead density checks.
pub const BODY_FONT_UNIFY_ANCHOR_COUNT: usize = 2;
pub const BODY_FONT_UNIFY_ANCHOR_MIN_HEIGHT_PT: f64 = 30.0;
pub const BODY_FONT_UNIFY_ANCHOR_MIN_WIDTH_RATIO: f64 = 0.58;
pub const BODY_FONT_UNIFY_ANCHOR_MAX_DENSITY: f64 = 1.18;
pub const BODY_FONT_UNIFY_TARGET_QUANTILE: f64 = 0.25;
pub const BODY_FONT_UNIFY_EXTREME_SMALL_RATIO: f64 = 0.82;
pub const BODY_FONT_UNIFY_EXTREME_SMALL_DELTA_PT: f64 = 1.6;
pub const BODY_FONT_UNIFY_MIN_FILTERED_COUNT: usize = 2;
pub const BODY_FONT_UNIFY_CANDIDATE_MIN_WIDTH_RATIO: f64 = 0.30;
pub const BODY_FONT_UNIFY_APPLY_TOLERANCE_PT: f64 = 0.08;
pub const BODY_FONT_UNIFY_MAX_SHRINK_PT: f64 = 1.25;
pub const BODY_FONT_UNIFY_GROW_DENSITY_LIMIT: f64 = 1.08;
pub const BODY_FONT_UNIFY_DIRECT_DENSE_MAX_LINES: i64 = 2;
pub const BODY_FONT_PRE_SMOOTH_MIN_LINES: i64 = 2;
pub const BODY_FONT_PRE_SMOOTH_MIN_HEIGHT_PT: f64 = 22.0;

// Annotation font unification. Captions and footnotes follow the same low-anchor
// rule as body text, but their seed fonts are already smaller via role scales.
pub const ANNOTATION_FONT_UNIFY_TARGET_QUANTILE: f64 = 0.25;
pub const ANNOTATION_FONT_UNIFY_EXTREME_SMALL_RATIO: f64 = 0.80;
pub const ANNOTATION_FONT_UNIFY_EXTREME_SMALL_DELTA_PT: f64 = 1.2;
pub const ANNOTATION_FONT_UNIFY_MIN_FILTERED_COUNT: usize = 2;
pub const ANNOTATION_FONT_UNIFY_APPLY_TOLERANCE_PT: f64 = 0.06;
pub const ANNOTATION_FONT_UNIFY_MAX_SHRINK_PT: f64 = 0.9;
pub const CAPTION_BODY_FONT_CAP_RATIO: f64 = 0.88;
pub const CAPTION_FONT_UNIFY_TARGET_BONUS_PT: f64 = 0.0;
pub const CAPTION_FONT_UNIFY_MAX_GROW_PT: f64 = 0.0;
pub const FOOTNOTE_BODY_FONT_CAP_RATIO: f64 = 0.82;
pub const FOOTNOTE_FONT_UNIFY_TARGET_BONUS_PT: f64 = 0.04;
pub const FOOTNOTE_FONT_UNIFY_MAX_GROW_PT: f64 = 0.08;
pub const ANNOTATION_UNDERFILLED_DENSITY_FLOOR_TRIGGER: f64 = BODY_UNDERFILLED_DENSITY_FLOOR_TRIGGER;
pub const ANNOTATION_UNDERFILLED_DENSITY_RECOVERY_TARGET: f64 = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET;
pub const ANNOTATION_UNDERFILLED_DENSITY_SAFE_MAX: f64 = BODY_UNDERFILLED_DENSITY_SAFE_MAX;
pub const ANNOTATION_UNDERFILLED_RECOVERY_MAX_ITERATIONS: i32 = 5;
pub const CAPTION_UNDERFILLED_RECOVERY_FONT_STEP_PT: f64 = 0.08;
pub const CAPTION_UNDERFILLED_RECOVERY_LEADING_STEP_EM: f64 = 0.025;
pub const CAPTION_UNDERFILLED_RECOVERY_LEADING_CAP_EM: f64 = 0.68;
pub const FOOTNOTE_UNDERFILLED_RECOVERY_FONT_STEP_PT: f64 = 0.12;
pub const FOOTNOTE_UNDERFILLED_RECOVERY_LEADING_STEP_EM: f64 = 0.025;
pub const FOOTNOTE_UNDERFILLED_RECOVERY_LEADING_CAP_EM: f64 = 0.66;

// Body leading recovery. The solver spends remaining vertical slack on line
// spacing after font growth, using source line count/pitch as soft signals.
pub const BODY_COMFORT_LEADING_MIN: f64 = 0.56;
pub const BODY_COMFORT_LEADING_DENSITY_MAX: f64 = 0.985;
pub const BODY_COMFORT_DENSITY_FLOOR_TRIGGER: f64 = BODY_UNDERFILLED_DENSITY_FLOOR_TRIGGER;
pub const BODY_COMFORT_DENSITY_RECOVERY_TARGET: f64 = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET;
pub const BODY_COMFORT_DENSITY_RECOVERY_TARGET_NO_SOURCE: f64 = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET_NO_SOURCE;
pub const BODY_COMFORT_DENSITY_RECOVERY_TARGET_SHORT: f64 = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET_SHORT;
pub const BODY_COMFORT_BASE_FILL: f64 = 0.70;
pub const BODY_COMFORT_TARGET_FILL_MAX: f64 = 0.90;
pub const BODY_COMFORT_LOW_SOURCE_LINE_COUNT_MAX: i64 = 5;
pub const BODY_COMFORT_LOW_SOURCE_LINE_TARGET_FILL_MAX: f64 = 0.78;
pub const BODY_COMFORT_LOW_SOURCE_LINE_LEADING_MAX: f64 = 0.70;
pub const BODY_COMFORT_LONG_LINE_THRESHOLD: i64 = 9;
pub const BODY_COMFORT_LONG_LEADING_MAX: f64 = 0.76;
pub const BODY_COMFORT_NO_SOURCE_LONG_LEADING_MAX: f64 = 0.74;
pub const BODY_COMFORT_SOURCE_LINE_LEADING_MAX: f64 = 1.02;
pub const BODY_COMFORT_SOLVER_MAX_ITERATIONS: i32 = 6;
pub const BODY_COMFORT_SOLVER_DENSITY_TOLERANCE: f64 = 0.002;
pub const BODY_COMFORT_SOLVER_MIN_BRACKET_WIDTH: f64 = 0.005;
pub const BODY_COMFORT_SOLVER_EXTRAPOLATION_MIN_FRACTION: f64 = 0.12;
pub const BODY_COMFORT_SOLVER_EXTRAPOLATION_MAX_FRACTION: f64 = 0.88;
pub const BODY_COMFORT_SLACK_NORMALIZER: f64 = 0.38;
pub const BODY_COMFORT_SOURCE_LINE_RATIO_OFFSET: f64 = 1.0;
pub const BODY_COMFORT_SOURCE_LINE_RATIO_MAX_GAP: f64 = 4.0;
pub const BODY_COMFORT_SOURCE_LEADING_MAX_GAP: f64 = 1.0;
pub const BODY_COMFORT_LINE_COUNT_BASE: f64 = 2.0;
pub const BODY_COMFORT_LINE_COUNT_NORMALIZER: f64 = 12.0;
pub const BODY_COMFORT_SLACK_GAIN_MAX: f64 = 0.08;
pub const BODY_COMFORT_SOURCE_LINE_GAIN_MAX: f64 = 0.12;
pub const BODY_COMFORT_SOURCE_PITCH_GAIN_MAX: f64 = 0.05;
pub const BODY_COMFORT_MULTI_LINE_GAIN_MAX: f64 = 0.10;
pub const BODY_COMFORT_FONT_GROWTH_GAIN_MAX: f64 = 0.03;
pub const BODY_COMFORT_FONT_GROWTH_MIN_LEADING_GAIN_MAX: f64 = 0.12;
pub const BODY_COMFORT_FONT_GROWTH_MIN_LEADING_RATE: f64 = 1.8;
pub const BODY_COMFORT_LEADING_GROWTH_BASE_MAX: f64 = 0.10;
pub const BODY_COMFORT_LEADING_GROWTH_SOURCE_MAX: f64 = 0.28;
pub const BODY_COMFORT_LEADING_GROWTH_LONG_TEXT_MAX: f64 = 0.08;
pub const BODY_COMFORT_LEADING_FONT_SPEND_PENALTY_MAX: f64 = 0.20;
pub const BODY_COMFORT_LEADING_GROWTH_MIN_AFTER_FONT_GROWTH: f64 = 0.04;
pub const BODY_COMFORT_PAGE_BASELINE_DENSITY_WEIGHT: f64 = 0.10;
pub const BODY_COMFORT_PAGE_BASELINE_MAX_DENSITY_DELTA: f64 = 0.20;
pub const BODY_COMFORT_SLACK_RESPONSE_RATE: f64 = 2.0;
pub const BODY_COMFORT_MULTI_LINE_WEIGHT_RATE: f64 = 0.42;
pub const BODY_COMFORT_SOURCE_LINE_RESPONSE_RATE: f64 = 0.78;
pub const BODY_COMFORT_SOURCE_LINE_VOLUME_BASE: f64 = 6.0;
pub const BODY_COMFORT_SOURCE_LINE_VOLUME_RESPONSE_RATE: f64 = 0.45;
pub const BODY_COMFORT_SOURCE_PITCH_RESPONSE_RATE: f64 = 3.2;
pub const BODY_COMFORT_LINE_COUNT_RESPONSE_RATE: f64 = 2.1;
pub const BODY_COMFORT_LONG_LINE_CAP_RESPONSE_RATE: f64 = 0.38;
pub const BODY_COMFORT_SOURCE_LINE_CAP_RESPONSE_RATE: f64 = 0.7;
pub const BODY_COMFORT_SOURCE_PITCH_CAP_RESPONSE_RATE: f64 = 1.1;
pub const BODY_COMFORT_FONT_GROWTH_NORMALIZER_PT: f64 = 1.2;

// Tall OCR bboxes often include source paragraph slack rather than usable text
// height. Use an effective height for density decisions so body rhythm remains
// closer to the page/book font target instead of chasing excessive whitespace.
pub const BODY_TALL_BBOX_MIN_LINES: i64 = 3;
pub const BODY_TALL_BBOX_MIN_HEIGHT_PT: f64 = 35.0;
pub const BODY_TALL_BBOX_HEIGHT_RATIO_TRIGGER: f64 = 1.8;
pub const BODY_TALL_BBOX_PAGE_RATIO_MULTIPLIER: f64 = 1.35;
pub const BODY_TALL_BBOX_EFFECTIVE_NATURAL_MULTIPLIER: f64 = 1.45;
pub const BODY_TALL_BBOX_EFFECTIVE_MIN_ORIGINAL_RATIO: f64 = 0.58;

// Adjacent collision protection. Once body font unification has selected a page
// body font, collision handling should not break that rhythm with a second font
// fit pass. It may only compress leading.
pub const BODY_COLLISION_UNIFIED_MIN_LEADING_EM: f64 = 0.52;
pub const BODY_COLLISION_UNIFIED_FONT_TOLERANCE_PT: f64 = 0.08;
