// setText 文案槽位 key 常量（评审 P1-3）。
//
// 这些 key 在主页已迁移为 React text-store 槽位（见 components/InlineErrorBox），
// 在详情页仍是真实 DOM id；两者共用同一份 key，禁止在调用点写字符串字面量。
// 新增槽位：在这里加常量，测试 tests/dom-text-keys.test.mjs 会校验唯一性与命名。

export const TEXT_KEYS = {
  detailErrorBox: "detail-error-box",
  detailFailureCategory: "detail-failure-category",
  detailFailureLastLogLine: "detail-failure-last-log-line",
  detailFailureRetryable: "detail-failure-retryable",
  detailFailureRootCause: "detail-failure-root-cause",
  detailFailureStage: "detail-failure-stage",
  detailFailureSuggestion: "detail-failure-suggestion",
  detailFailureSummary: "detail-failure-summary",
  detailFinishedAt: "detail-finished-at",
  detailMarkdownImageCount: "detail-markdown-image-count",
  detailMarkdownImagesBaseUrl: "detail-markdown-images-base-url",
  detailMarkdownJsonUrl: "detail-markdown-json-url",
  detailMarkdownPreview: "detail-markdown-preview",
  detailMarkdownRawUrl: "detail-markdown-raw-url",
  detailMarkdownStatus: "detail-markdown-status",
  detailRerunStatus: "detail-rerun-status",
  detailRuntimeCurrentStage: "detail-runtime-current-stage",
  detailRuntimeInputProtocol: "detail-runtime-input-protocol",
  detailRuntimeLastTransition: "detail-runtime-last-transition",
  detailRuntimeMathMode: "detail-runtime-math-mode",
  detailRuntimeRetryCount: "detail-runtime-retry-count",
  detailRuntimeStageElapsed: "detail-runtime-stage-elapsed",
  detailRuntimeStageSpecVersion: "detail-runtime-stage-spec-version",
  detailRuntimeTerminalReason: "detail-runtime-terminal-reason",
  detailRuntimeTotalElapsed: "detail-runtime-total-elapsed",
  detailStageDetail: "detail-stage-detail",
  detailStatusSummary: "detail-status-summary",
  errorBox: "error-box",
  eventsStatus: "events-status",
  failureCategory: "failure-category",
  failureLastLogLine: "failure-last-log-line",
  failureRetryable: "failure-retryable",
  failureRootCause: "failure-root-cause",
  failureStage: "failure-stage",
  failureSuggestion: "failure-suggestion",
  failureSummary: "failure-summary",
  jobFinishedAt: "job-finished-at",
  jobId: "job-id",
  jobStageDetail: "job-stage-detail",
  jobSummary: "job-summary",
  queryJobDuration: "query-job-duration",
  runtimeCurrentStage: "runtime-current-stage",
  runtimeInputProtocol: "runtime-input-protocol",
  runtimeLastTransition: "runtime-last-transition",
  runtimeMathMode: "runtime-math-mode",
  runtimeRetryCount: "runtime-retry-count",
  runtimeStageElapsed: "runtime-stage-elapsed",
  runtimeStageSpecVersion: "runtime-stage-spec-version",
  runtimeTerminalReason: "runtime-terminal-reason",
  runtimeTotalElapsed: "runtime-total-elapsed",
  statusDetailJobId: "status-detail-job-id",
} as const;

export type TextKey = (typeof TEXT_KEYS)[keyof typeof TEXT_KEYS];
