[package]
name = "rendering_output"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.19"
mupdf = { version = "0.8", default-features = false, features = ["base14-fonts"] }
pathdiff = "0.2"
rendering_core = { path = "../rendering_core" }
rendering_reader = { path = "../rendering_reader" }
rendering_writer = { path = "../rendering_writer" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
base64 = "0.22"
