//! Shared support for the differential (golden replay) tests.
//!
//! Loads `tests/corpus.json` (generated by
//! `backend/rendering_core/differential/gen_corpus.py`), deserializes each case
//! into lightweight DTOs (this module only — the lib stays serde-free), converts
//! them into lib types, and provides float/vector comparison helpers.
//!
//! Each differential test binary only uses a subset of the helpers/DTOs below,
//! so dead_code is allowed at the module level.

#![allow(dead_code)]

use std::collections::HashMap;
use std::sync::OnceLock;

use rendering_core::item::{FormulaEntry, Item, Line, Span};
use rendering_core::page::{ImageInfo, PageSnapshot, TextTrace};
use rendering_core::profile::{
    ImageBackgroundProfile, OcrBlockProfile, PageGeometryProfile, RenderPageKind,
    RenderPageProfile, TextLayerProfile, VectorLayerProfile,
};
use rendering_core::rect::Rect;
use serde::Deserialize;
use serde_json::Value;

// --- corpus loading ----------------------------------------------------------

#[derive(Deserialize)]
pub struct Case {
    pub input: Value,
    pub expected: Value,
}

#[derive(Deserialize)]
pub struct Corpus {
    pub schema: String,
    pub seed: u64,
    pub cases: HashMap<String, Vec<Case>>,
}

fn load_corpus() -> &'static Corpus {
    static CORPUS: OnceLock<Corpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../corpus.json");
        serde_json::from_str(raw).expect("failed to parse corpus.json")
    })
}

pub fn corpus() -> &'static Corpus {
    load_corpus()
}

pub fn cases<'a>(corpus: &'a Corpus, fn_id: &str) -> &'a Vec<Case> {
    corpus
        .cases
        .get(fn_id)
        .unwrap_or_else(|| panic!("fn_id not present in corpus: {fn_id}"))
}

pub fn from_value<T: serde::de::DeserializeOwned>(v: &Value) -> T {
    serde_json::from_value(v.clone()).unwrap_or_else(|e| panic!("deserialize failed: {e}"))
}

// --- item DTO ----------------------------------------------------------------

#[derive(Deserialize)]
pub struct DerivedDto {
    #[serde(default)]
    pub role: Option<String>,
}

#[derive(Deserialize)]
pub struct SpanDto {
    #[serde(default, rename = "type")]
    pub span_type: String,
    #[serde(default)]
    pub content: String,
}

#[derive(Deserialize)]
pub struct LineDto {
    #[serde(default)]
    pub bbox: Option<[f64; 4]>,
    #[serde(default)]
    pub spans: Vec<SpanDto>,
}

#[derive(Deserialize)]
pub struct FormulaDto {
    #[serde(default)]
    pub placeholder: String,
    #[serde(default)]
    pub formula_text: String,
}

#[derive(Deserialize)]
pub struct ItemDto {
    #[serde(default)]
    pub bbox: Option<[f64; 4]>,
    #[serde(default)]
    pub lines: Vec<LineDto>,
    #[serde(default)]
    pub source_text: String,
    #[serde(default)]
    pub layout_role: Option<String>,
    #[serde(default)]
    pub semantic_role: Option<String>,
    #[serde(default)]
    pub structure_role: Option<String>,
    #[serde(default)]
    pub block_kind: Option<String>,
    #[serde(default)]
    pub block_type: Option<String>,
    #[serde(default)]
    pub sub_type: Option<String>,
    #[serde(default)]
    pub normalized_sub_type: Option<String>,
    #[serde(default)]
    pub raw_block_type: Option<String>,
    #[serde(default)]
    pub derived: Option<DerivedDto>,
    #[serde(default)]
    pub policy_translate: Option<bool>,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub formula_map: Vec<FormulaDto>,
    #[serde(default, rename = "_is_body_text_candidate")]
    pub is_body_text_candidate: bool,
    #[serde(default, rename = "_wide_aspect_body_text")]
    pub wide_aspect_body_text: bool,
    #[serde(default, rename = "_cover_with_inner_bbox")]
    pub cover_with_inner_bbox: bool,
}

pub fn to_formula_map(dtos: &[FormulaDto]) -> Vec<FormulaEntry> {
    dtos.iter()
        .map(|f| FormulaEntry {
            placeholder: f.placeholder.clone(),
            formula_text: f.formula_text.clone(),
        })
        .collect()
}

pub fn to_formula_pairs(dtos: &[FormulaDto]) -> Vec<(String, String)> {
    dtos.iter()
        .map(|f| (f.placeholder.clone(), f.formula_text.clone()))
        .collect()
}

impl LineDto {
    pub fn to_line(&self) -> Line {
        Line {
            bbox: self.bbox,
            spans: self
                .spans
                .iter()
                .map(|s| Span {
                    span_type: s.span_type.clone(),
                    content: s.content.clone(),
                })
                .collect(),
        }
    }
}

impl ItemDto {
    pub fn to_item(&self) -> Item {
        Item {
            bbox: self.bbox,
            lines: self
                .lines
                .iter()
                .map(|l| Line {
                    bbox: l.bbox,
                    spans: l
                        .spans
                        .iter()
                        .map(|s| Span {
                            span_type: s.span_type.clone(),
                            content: s.content.clone(),
                        })
                        .collect(),
                })
                .collect(),
            source_text: self.source_text.clone(),
            layout_role: self.layout_role.clone(),
            semantic_role: self.semantic_role.clone(),
            structure_role: self.structure_role.clone(),
            block_kind: self.block_kind.clone(),
            block_type: self.block_type.clone(),
            sub_type: self.sub_type.clone(),
            normalized_sub_type: self.normalized_sub_type.clone(),
            raw_block_type: self.raw_block_type.clone(),
            derived_role: self.derived.as_ref().and_then(|d| d.role.clone()),
            policy_translate: self.policy_translate,
            tags: self.tags.clone(),
            formula_map: to_formula_map(&self.formula_map),
            is_body_text_candidate: self.is_body_text_candidate,
            wide_aspect_body_text: self.wide_aspect_body_text,
            cover_with_inner_bbox: self.cover_with_inner_bbox,
            ..Default::default()
        }
    }
}

// --- profile DTOs ------------------------------------------------------------

#[derive(Deserialize)]
pub struct GeometryDto {
    pub page_index: i64,
    pub width_pt: f64,
    pub height_pt: f64,
    pub rotation: i64,
    pub cropbox: [f64; 4],
}

#[derive(Deserialize)]
pub struct TextLayerDto {
    pub visible_traces: i64,
    pub hidden_traces: i64,
    pub has_visible_text: bool,
    pub has_hidden_text: bool,
    pub editable: bool,
}

#[derive(Deserialize)]
pub struct ImageBackgroundDto {
    pub has_large_background: bool,
    pub coverage_ratio: f64,
    pub xref: Option<i64>,
    pub bbox: Option<[f64; 4]>,
}

#[derive(Deserialize)]
pub struct VectorLayerDto {
    pub drawing_count: i64,
    pub vector_heavy: bool,
    pub cover_only_preferred: bool,
}

#[derive(Deserialize)]
pub struct OcrBlocksDto {
    pub block_count: i64,
    pub valid_bbox_count: i64,
    pub total_bbox_area: f64,
    pub page_area_ratio: f64,
}

#[derive(Deserialize)]
pub struct ProfileDto {
    pub geometry: GeometryDto,
    pub text_layer: TextLayerDto,
    pub image_background: ImageBackgroundDto,
    pub vector_layer: VectorLayerDto,
    pub ocr_blocks: OcrBlocksDto,
    pub kind: String,
}

pub fn parse_kind(s: &str) -> RenderPageKind {
    match s {
        "editable_text" => RenderPageKind::EditableText,
        "scan_image" => RenderPageKind::ScanImage,
        "pseudo_editable_scan" => RenderPageKind::PseudoEditableScan,
        "vector_heavy" => RenderPageKind::VectorHeavy,
        "mixed_complex" => RenderPageKind::MixedComplex,
        other => panic!("unknown RenderPageKind: {other}"),
    }
}

impl TextLayerDto {
    pub fn to_text_layer(&self) -> TextLayerProfile {
        TextLayerProfile {
            visible_traces: self.visible_traces,
            hidden_traces: self.hidden_traces,
            has_visible_text: self.has_visible_text,
            has_hidden_text: self.has_hidden_text,
            editable: self.editable,
        }
    }
}

impl ImageBackgroundDto {
    pub fn to_image_background(&self) -> ImageBackgroundProfile {
        ImageBackgroundProfile {
            has_large_background: self.has_large_background,
            coverage_ratio: self.coverage_ratio,
            xref: self.xref,
            bbox: self.bbox,
        }
    }
}

impl VectorLayerDto {
    pub fn to_vector_layer(&self) -> VectorLayerProfile {
        VectorLayerProfile {
            drawing_count: self.drawing_count,
            vector_heavy: self.vector_heavy,
            cover_only_preferred: self.cover_only_preferred,
        }
    }
}

impl OcrBlocksDto {
    pub fn to_ocr_blocks(&self) -> OcrBlockProfile {
        OcrBlockProfile {
            block_count: self.block_count,
            valid_bbox_count: self.valid_bbox_count,
            total_bbox_area: self.total_bbox_area,
            page_area_ratio: self.page_area_ratio,
        }
    }
}

impl ProfileDto {
    pub fn to_profile(&self) -> RenderPageProfile {
        RenderPageProfile {
            geometry: PageGeometryProfile {
                page_index: self.geometry.page_index,
                width_pt: self.geometry.width_pt,
                height_pt: self.geometry.height_pt,
                rotation: self.geometry.rotation,
                cropbox: self.geometry.cropbox,
            },
            text_layer: self.text_layer.to_text_layer(),
            image_background: self.image_background.to_image_background(),
            vector_layer: self.vector_layer.to_vector_layer(),
            ocr_blocks: OcrBlockProfile {
                block_count: self.ocr_blocks.block_count,
                valid_bbox_count: self.ocr_blocks.valid_bbox_count,
                total_bbox_area: self.ocr_blocks.total_bbox_area,
                page_area_ratio: self.ocr_blocks.page_area_ratio,
            },
            kind: parse_kind(&self.kind),
        }
    }
}

// --- PageSnapshot DTOs (Phase 3 profile collectors) --------------------------

#[derive(Deserialize)]
pub struct TextTraceDto {
    #[serde(default, rename = "type")]
    pub trace_type: i64,
    #[serde(default)]
    pub opacity: f64,
}

#[derive(Deserialize)]
pub struct ImageInfoDto {
    #[serde(default)]
    pub xref: i64,
    #[serde(default)]
    pub bbox: [f64; 4],
}

#[derive(Deserialize)]
pub struct PageSnapshotDto {
    pub number: i64,
    pub rotation: i64,
    pub rect: [f64; 4],
    pub cropbox: [f64; 4],
    #[serde(default)]
    pub text_traces: Vec<TextTraceDto>,
    #[serde(default)]
    pub word_count: i64,
    #[serde(default)]
    pub drawing_count: i64,
    #[serde(default)]
    pub image_infos: Vec<ImageInfoDto>,
    #[serde(default)]
    pub image_entries: Vec<i64>,
    #[serde(default)]
    pub image_rects: HashMap<String, Vec<[f64; 4]>>,
}

impl PageSnapshotDto {
    pub fn to_snapshot(&self) -> PageSnapshot {
        PageSnapshot {
            number: self.number,
            rotation: self.rotation,
            rect: Rect::new(self.rect[0], self.rect[1], self.rect[2], self.rect[3]),
            cropbox: Rect::new(self.cropbox[0], self.cropbox[1], self.cropbox[2], self.cropbox[3]),
            text_traces: self
                .text_traces
                .iter()
                .map(|t| TextTrace {
                    trace_type: t.trace_type,
                    opacity: t.opacity,
                })
                .collect(),
            word_count: self.word_count,
            drawing_count: self.drawing_count,
            image_infos: self
                .image_infos
                .iter()
                .map(|i| ImageInfo {
                    xref: i.xref,
                    bbox: Rect::new(i.bbox[0], i.bbox[1], i.bbox[2], i.bbox[3]),
                })
                .collect(),
            image_entries: self.image_entries.clone(),
            image_rects: self
                .image_rects
                .iter()
                .map(|(k, v)| {
                    (
                        k.parse::<i64>().unwrap_or(0),
                        v.iter()
                            .map(|b| Rect::new(b[0], b[1], b[2], b[3]))
                            .collect::<Vec<Rect>>(),
                    )
                })
                .collect::<HashMap<i64, Vec<Rect>>>(),
        }
    }
}

#[derive(Debug, Deserialize)]
pub struct PrimaryImageDto {
    pub xref: i64,
    pub bbox: [f64; 4],
}

#[derive(Deserialize)]
pub struct RoutePartDto {
    pub redaction: String,
    pub background: String,
    pub compose: String,
    pub layout: String,
    pub reason: String,
}

#[derive(Deserialize)]
pub struct ClassificationDto {
    pub kind: String,
    pub large_background_image: bool,
    pub visible_text_traces: i64,
    pub hidden_text_traces: i64,
    pub drawing_count: i64,
    pub background_coverage_ratio: f64,
    pub route: RoutePartDto,
}

// --- comparison helpers ------------------------------------------------------

pub fn assert_close_f64(actual: f64, expected: f64) {
    let tol = 1e-6 * expected.abs().max(1.0);
    assert!(
        (actual - expected).abs() <= tol,
        "float mismatch: actual={actual}, expected={expected}, tol={tol}"
    );
}

pub fn assert_close_f64_slice(actual: &[f64], expected: &[f64]) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "slice length mismatch: actual={actual:?}, expected={expected:?}"
    );
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let tol = 1e-6 * e.abs().max(1.0);
        assert!(
            (a - e).abs() <= tol,
            "float mismatch at index {i}: actual={a}, expected={e}, tol={tol}"
        );
    }
}

pub fn assert_close_i64(actual: i64, expected: i64) {
    assert_eq!(actual, expected, "int mismatch");
}

/// A result field accessor that deserializes `expected` into a named struct
/// for chinese_body_fit / fit_decision result dicts.
#[derive(Deserialize)]
pub struct ChineseBodyFitExpected {
    pub font_size_pt: f64,
    pub estimated_height_pt: f64,
    pub line_count: i64,
    pub overflow_ratio: f64,
    pub formula_ratio: f64,
    pub confidence: f64,
    pub max_safe_shrink_pt: f64,
}

#[derive(Deserialize)]
pub struct FitDecisionExpected {
    pub font_size_pt: f64,
    pub mode: String,
    pub confidence: f64,
    pub reason_codes: Vec<String>,
    pub estimated_height_pt: f64,
    pub overflow_ratio: f64,
    pub formula_ratio: f64,
    pub growth_pt: f64,
    pub shrink_pt: f64,
}

#[derive(Deserialize)]
pub struct AnalyzeStatsExpected {
    pub word_count: i64,
    pub zh_char_count: i64,
    pub formula_count: i64,
    pub raw_math_count: i64,
    pub latex_command_count: i64,
    pub placeholder_count: i64,
    pub protected_formula_count: i64,
}

#[derive(Deserialize)]
pub struct RouteExpected {
    pub redaction: String,
    pub background: String,
    pub compose: String,
    pub layout: String,
    pub reason: String,
    pub render_mode_hint: String,
    pub text_cleanup: String,
    pub overlay_fallback: String,
}
