//! Batched first-line-indent differential: `rendering_reader::indent`
//! (`detect_first_line_indents`) vs fitz reference values stored in
//! `tests/render_corpus.json` (generated by `differential/gen_render_corpus.py`).
//!
//! The corpus records, per gated candidate, the indent fitz computes from its
//! own display-list pixmap path (`fitz_dl_indent_pt`); render_diff.rs already
//! proves mupdf-rs dl pixels are byte-identical to fitz's. This test replays
//! the batched entry point — grouped per page so each display list is built
//! once — and asserts it reproduces the same indents in input order.

use std::collections::BTreeMap;
use std::path::Path;

use rendering_reader::indent::{detect_first_line_indents, INDENT_RENDER_SCALE};
use serde::Deserialize;

#[derive(Deserialize)]
struct RenderCorpus {
    schema: String,
    render_scale: f64,
    candidates: Vec<Candidate>,
}

#[derive(Clone, Deserialize)]
struct Candidate {
    pdf: String,
    page: i64,
    bbox: [f64; 4],
    font_size_pt: f64,
    fitz_dl_indent_pt: f64,
}

const CORPUS: &str = include_str!("render_corpus.json");
const GOLDEN_ROOT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../resources/samples/golden-pdfs"
);

fn corpus() -> RenderCorpus {
    serde_json::from_str(CORPUS).expect("parse render_corpus.json")
}

type PageCandidates = BTreeMap<i64, Vec<([f64; 4], f64)>>;

/// Corpus schema sanity + scale contract: the batch entry point is hard-wired
/// to INDENT_RENDER_SCALE, which must equal the corpus generation scale.
#[test]
fn corpus_meta_matches_batch_scale() {
    let corpus = corpus();
    assert_eq!(corpus.schema, "retainpdf_render_corpus_v1");
    assert_eq!(corpus.render_scale, INDENT_RENDER_SCALE as f64);
    assert!(!corpus.candidates.is_empty());
}

#[test]
fn batch_indents_match_fitz() {
    let corpus = corpus();
    // Group candidates per pdf (each pdf opened once), keeping per-page input
    // order; results must keep that order so candidates map back by position.
    let mut per_pdf: BTreeMap<String, Vec<Candidate>> = BTreeMap::new();
    for cand in corpus.candidates.clone() {
        per_pdf.entry(cand.pdf.clone()).or_default().push(cand);
    }
    let mut checked = 0u32;
    let mut nonzero = 0u32;
    for (pdf, cands) in &per_pdf {
        let doc = rendering_reader::reader::open(&Path::new(GOLDEN_ROOT).join(pdf))
            .unwrap_or_else(|e| panic!("open {pdf}: {e}"));
        let mut by_page: PageCandidates = BTreeMap::new();
        for cand in cands {
            by_page
                .entry(cand.page)
                .or_default()
                .push((cand.bbox, cand.font_size_pt));
        }
        let pages: Vec<i64> = by_page.keys().copied().collect();
        let result = detect_first_line_indents(&doc, &pages, &by_page);
        for (page_idx, entries) in &result {
            assert_eq!(
                entries.len(),
                by_page[page_idx].len(),
                "entry count mismatch {pdf} p{page_idx}"
            );
            assert!(
                entries.iter().all(|e| e.is_some()),
                "readable page must not contain skipped entries ({pdf} p{page_idx})"
            );
        }
        for cand in cands {
            let entries = &result[&cand.page];
            let slot = by_page[&cand.page]
                .iter()
                .position(|&(b, _)| b == cand.bbox)
                .expect("candidate bbox present");
            let indent = entries[slot].expect("rendered candidate present");
            assert!(
                (indent - cand.fitz_dl_indent_pt).abs() <= 1e-6,
                "batch indent {pdf} p{}: rust={indent} fitz={}",
                cand.page,
                cand.fitz_dl_indent_pt
            );
            if cand.fitz_dl_indent_pt != 0.0 {
                nonzero += 1;
            }
            checked += 1;
        }
    }
    assert_eq!(checked as usize, corpus.candidates.len());
    assert!(nonzero > 0, "corpus has no nonzero indent candidates");
}

/// Boundary behavior: an out-of-page bbox yields empty samples -> 0.0 (not a
/// skip), and an unreadable page index yields None entries for its candidates.
#[test]
fn batch_boundary_clips_and_pages() {
    let corpus = corpus();
    let first = &corpus.candidates[0];
    let doc = rendering_reader::reader::open(&Path::new(GOLDEN_ROOT).join(&first.pdf))
        .expect("open golden pdf");

    let font = first.font_size_pt;
    let real_bbox = first.bbox;
    let mut by_page: PageCandidates = BTreeMap::new();
    by_page.insert(
        first.page,
        vec![
            (real_bbox, font),
            ([10000.0, 10000.0, 10100.0, 10100.0], font), // outside page bounds
        ],
    );
    by_page.insert(i64::MAX, vec![([0.0, 0.0, 10.0, 10.0], font)]); // unreadable

    let pages: Vec<i64> = by_page.keys().copied().collect();
    let result = detect_first_line_indents(&doc, &pages, &by_page);

    let live = &result[&first.page];
    assert_eq!(live.len(), 2);
    assert!(live[0].is_some(), "in-page candidate must render");
    assert_eq!(live[1], Some(0.0), "out-of-page clip degrades to 0.0");

    let unreadable = &result[&i64::MAX];
    assert_eq!(unreadable.len(), 1);
    assert_eq!(unreadable[0], None, "unreadable page marks entries skipped");
}
