//! Phase 5B render differential: mupdf-rs clipped gray renders vs fitz.
//!
//! Replays `tests/render_corpus.json` (generated by
//! `differential/gen_render_corpus.py`) against the same golden PDFs:
//!   1. Pixel parity — `render::render_page_clip_gray` and
//!      `render::render_display_list_clip_gray` samples match the fitz
//!      page-/display-list pixels stored in the corpus (byte-for-byte; both wrap
//!      the same MuPDF C engine).
//!   2. Cross-path parity — for every candidate the two mupdf-rs renderers
//!      produce identical samples (fitz dl pixels are only stored for a subset).
//!   3. Result parity — `rendering_core::first_line_indent`
//!      (`detect_first_line_indent_pt_from_samples`) fed the mupdf-rs pixels
//!      reproduces fitz's `fitz_page_indent_pt` / `fitz_dl_indent_pt`.

use std::path::Path;

use base64::Engine;
use mupdf::{DisplayList, Document, Rect};
use rendering_core::first_line_indent::detect_first_line_indent_pt_from_samples;
use rendering_reader::reader::open as open_doc;
use rendering_reader::render::{render_display_list_clip_gray, render_page_clip_gray};
use serde::Deserialize;

#[derive(Deserialize)]
struct RenderCorpus {
    schema: String,
    render_scale: f64,
    candidates: Vec<Candidate>,
}

#[derive(Deserialize)]
struct Candidate {
    pdf: String,
    page: i64,
    bbox: [f64; 4],
    font_size_pt: f64,
    fitz_page_indent_pt: f64,
    fitz_dl_indent_pt: f64,
    #[serde(default)]
    pixels: Option<Pixels>,
}

#[derive(Deserialize)]
struct Pixels {
    page: PixelEntry,
    dl: PixelEntry,
}

#[derive(Deserialize)]
struct PixelEntry {
    w: u32,
    h: u32,
    samples_b64: String,
}

const CORPUS: &str = include_str!("render_corpus.json");
const GOLDEN_ROOT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../resources/samples/golden-pdfs"
);

fn corpus() -> RenderCorpus {
    serde_json::from_str(CORPUS).expect("parse render_corpus.json")
}

fn decode(b64: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(b64.as_bytes())
        .unwrap_or_else(|e| panic!("base64 decode failed: {e}"))
}

fn to_mupdf_rect(bbox: &[f64; 4]) -> Rect {
    Rect::new(bbox[0] as f32, bbox[1] as f32, bbox[2] as f32, bbox[3] as f32)
}

fn golden_doc(name: &str) -> Document {
    open_doc(&Path::new(GOLDEN_ROOT).join(name)).unwrap_or_else(|e| panic!("open {name}: {e}"))
}

/// Iterate candidates in corpus order, caching the document per pdf and the
/// display list per page, and hand each candidate to `f`.
fn for_each_candidate<F: FnMut(&Candidate, &Document, &DisplayList)>(corpus: &RenderCorpus, mut f: F) {
    let mut cur_doc: Option<(String, Document)> = None;
    let mut cur_dl: Option<(String, i64, DisplayList)> = None;
    for cand in &corpus.candidates {
        if cur_doc.as_ref().map(|(n, _)| n != &cand.pdf).unwrap_or(true) {
            cur_doc = Some((cand.pdf.clone(), golden_doc(&cand.pdf)));
        }
        let dl_stale = cur_dl
            .as_ref()
            .map(|(n, p, _)| n != &cand.pdf || *p != cand.page)
            .unwrap_or(true);
        if dl_stale {
            let doc = cur_doc.as_ref().unwrap().1.clone();
            let dl = doc
                .load_page(cand.page as i32)
                .expect("load_page")
                .to_display_list(false)
                .expect("to_display_list");
            cur_dl = Some((cand.pdf.clone(), cand.page, dl));
        }
        f(cand, &cur_doc.as_ref().unwrap().1, &cur_dl.as_ref().unwrap().2);
    }
}

#[test]
fn rust_render_matches_fitz_pixels() {
    let corpus = corpus();
    let scale = corpus.render_scale as f32;
    let mut checked = 0u32;
    for cand in corpus.candidates.iter().filter(|c| c.pixels.is_some()) {
        let px = cand.pixels.as_ref().unwrap();
        let doc = golden_doc(&cand.pdf);
        let clip = to_mupdf_rect(&cand.bbox);
        let page_out = render_page_clip_gray(&doc, cand.page as i32, Some(&clip), scale)
            .unwrap_or_else(|e| panic!("page render {} p{}: {e}", cand.pdf, cand.page));
        let dl = doc
            .load_page(cand.page as i32)
            .unwrap()
            .to_display_list(false)
            .unwrap();
        let dl_out = render_display_list_clip_gray(&dl, Some(&clip), scale)
            .unwrap_or_else(|e| panic!("dl render {} p{}: {e}", cand.pdf, cand.page));
        assert_eq!(
            (page_out.width, page_out.height),
            (px.page.w, px.page.h),
            "page dims {} p{}",
            cand.pdf,
            cand.page
        );
        assert_eq!(
            (dl_out.width, dl_out.height),
            (px.dl.w, px.dl.h),
            "dl dims {} p{}",
            cand.pdf,
            cand.page
        );
        assert_eq!(
            page_out.samples,
            decode(&px.page.samples_b64),
            "page pixels {} p{}",
            cand.pdf,
            cand.page
        );
        assert_eq!(
            dl_out.samples,
            decode(&px.dl.samples_b64),
            "dl pixels {} p{}",
            cand.pdf,
            cand.page
        );
        checked += 1;
    }
    assert!(checked > 0, "no pixel entries in corpus");
}

#[test]
fn rust_dl_render_matches_rust_page_render() {
    let corpus = corpus();
    let scale = corpus.render_scale as f32;
    let mut checked = 0u32;
    for_each_candidate(&corpus, |cand, doc, dl| {
        let clip = to_mupdf_rect(&cand.bbox);
        let page_out = render_page_clip_gray(doc, cand.page as i32, Some(&clip), scale).unwrap();
        let dl_out = render_display_list_clip_gray(dl, Some(&clip), scale).unwrap();
        assert_eq!(
            (page_out.width, page_out.height),
            (dl_out.width, dl_out.height),
            "dims {} p{}",
            cand.pdf,
            cand.page
        );
        assert_eq!(
            page_out.samples, dl_out.samples,
            "dl-vs-page pixels {} p{}",
            cand.pdf,
            cand.page
        );
        checked += 1;
    });
    assert!(checked == corpus.candidates.len() as u32, "checked {checked}");
}

#[test]
fn rust_indent_matches_fitz() {
    let corpus = corpus();
    let scale = corpus.render_scale as f32;
    let tol = 1e-6;
    let mut checked = 0u32;
    let mut nonzero = 0u32;
    for_each_candidate(&corpus, |cand, doc, dl| {
        let clip = to_mupdf_rect(&cand.bbox);
        let page_out = render_page_clip_gray(doc, cand.page as i32, Some(&clip), scale).unwrap();
        let dl_out = render_display_list_clip_gray(dl, Some(&clip), scale).unwrap();
        let rust_page = detect_first_line_indent_pt_from_samples(
            &page_out.samples,
            page_out.width as usize,
            page_out.height as usize,
            cand.font_size_pt,
        );
        let rust_dl = detect_first_line_indent_pt_from_samples(
            &dl_out.samples,
            dl_out.width as usize,
            dl_out.height as usize,
            cand.font_size_pt,
        );
        assert!(
            (rust_page - cand.fitz_page_indent_pt).abs() <= tol,
            "page indent {} p{}: rust={rust_page} fitz={}",
            cand.pdf,
            cand.page,
            cand.fitz_page_indent_pt
        );
        assert!(
            (rust_dl - cand.fitz_dl_indent_pt).abs() <= tol,
            "dl indent {} p{}: rust={rust_dl} fitz={}",
            cand.pdf,
            cand.page,
            cand.fitz_dl_indent_pt
        );
        if cand.fitz_page_indent_pt != 0.0 {
            nonzero += 1;
        }
        checked += 1;
    });
    assert!(checked == corpus.candidates.len() as u32, "checked {checked}");
    assert!(nonzero > 0, "corpus has no nonzero indent candidates");
}

#[test]
fn corpus_meta_is_sane() {
    let corpus = corpus();
    assert_eq!(corpus.schema, "retainpdf_render_corpus_v1");
    assert_eq!(corpus.render_scale, 2.0);
    assert!(!corpus.candidates.is_empty());
    // fitz's page- and display-list paths must agree where both are recorded.
    for cand in &corpus.candidates {
        assert_eq!(
            cand.fitz_page_indent_pt, cand.fitz_dl_indent_pt,
            "fitz page-vs-dl indent mismatch {} p{}",
            cand.pdf, cand.page
        );
    }
}
