//! Shared support for the rendering_writer differential tests.
//!
//! Loads `tests/write_corpus.json` (generated by
//! `differential/gen_write_corpus.py`, which runs the REAL production pikepdf
//! strip pipeline) into serde DTOs and measures the same semantic facts on the
//! mupdf-rs side: per-page word count (fitz vs mupdf-rs extraction paths differ
//! up to ~5%, so 10% relative tolerance) and ink ratio (both wrap the same
//! MuPDF C renderer, so ±0.02 absolute).

#![allow(dead_code)]

use std::collections::HashMap;
use std::sync::OnceLock;

use base64::Engine;
use mupdf::{Document, TextExtractOptions, TextPageFlags};
use rendering_core::source_cleanup::hit_test::RectTuple;
use rendering_reader::render::render_page_clip_gray;
use serde::Deserialize;

/// Relative word-count tolerance vs fitz `get_text("words")` (different
/// extraction path — see rendering_reader's reader.rs).
pub const WORD_COUNT_TOLERANCE: f64 = 0.10;
/// Absolute ink-ratio tolerance. Both engines wrap MuPDF; the write path only
/// needs semantic equivalence.
pub const INK_RATIO_TOLERANCE: f64 = 0.02;

// --- corpus loading ----------------------------------------------------------

#[derive(Deserialize)]
pub struct WriteCorpus {
    pub schema: String,
    pub render_scale: f64,
    pub ink_threshold: u8,
    pub cases: Vec<WriteCase>,
    #[serde(default)]
    pub subset_cases: Vec<SubsetCase>,
    #[serde(default)]
    pub overlay_cases: Vec<OverlayCase>,
    #[serde(default)]
    pub image_cases: Vec<ImageCase>,
    #[serde(default)]
    pub prep_cases: Vec<PrepCase>,
}

/// Untagged union of the preparation cases (hidden_text / sanitize),
/// disambiguated by `expected.text_objects_removed` (hidden only).
#[derive(Deserialize)]
#[serde(untagged)]
pub enum PrepCase {
    Hidden(HiddenTextCase),
    Sanitize(SanitizeCase),
}

#[derive(Deserialize)]
pub struct HiddenTextCase {
    pub name: String,
    pub input_pdf_b64: String,
    pub expected: HiddenTextExpected,
}

#[derive(Deserialize)]
pub struct HiddenTextExpected {
    pub pages_changed: usize,
    pub text_objects_removed: usize,
    pub input: PageFacts,
    pub output: PageFacts,
}

#[derive(Deserialize)]
pub struct SanitizeCase {
    pub name: String,
    pub input_pdf_b64: String,
    pub expected: SanitizeExpected,
}

#[derive(Deserialize)]
pub struct SanitizeExpected {
    pub invalid_image_xobjects: usize,
    pub pages_changed: usize,
    pub input: PageFacts,
    pub output: PageFacts,
    pub output_image_count: usize,
    pub output_invalid_image_count: usize,
    #[serde(default)]
    pub output_xobject_subtypes: Vec<Vec<String>>,
}

#[derive(Deserialize)]
pub struct ImageCase {
    pub name: String,
    pub input_pdf_b64: String,
    pub dpi: i32,
    pub expected: ImageExpected,
}

#[derive(Deserialize)]
pub struct ImageExpected {
    pub changed: bool,
    pub input: PageFacts,
    pub output: PageFacts,
    pub input_image: ImageFact,
    pub output_image: ImageFact,
}

#[derive(Deserialize)]
pub struct ImageFact {
    pub width: i64,
    pub height: i64,
    pub encoded_len: usize,
    #[serde(default)]
    pub filter: String,
}

#[derive(Deserialize)]
pub struct OverlayCase {
    pub name: String,
    pub input_pdf_b64: String,
    pub overlay_pdf_b64: String,
    pub expected: OverlayExpected,
}

#[derive(Deserialize)]
pub struct OverlayExpected {
    pub pages_merged: usize,
    pub input: PageFacts,
    pub output: PageFacts,
}

#[derive(Deserialize)]
pub struct SubsetCase {
    pub name: String,
    pub input_pdf_b64: String,
    pub start_page: i64,
    pub end_page: i64,
    pub expected: SubsetExpected,
}

#[derive(Deserialize)]
pub struct SubsetExpected {
    pub input: PageFacts,
    pub output: PageFacts,
    pub output_page_count: usize,
}

#[derive(Deserialize)]
pub struct WriteCase {
    pub name: String,
    pub input_pdf_b64: String,
    pub page_count: usize,
    pub page_rects: HashMap<String, Vec<Vec<f64>>>,
    #[serde(default)]
    pub page_protected_rects: HashMap<String, Vec<Vec<f64>>>,
    pub recurse_forms: bool,
    pub expected: WriteExpected,
}

#[derive(Deserialize)]
pub struct WriteExpected {
    pub pages_changed: usize,
    pub text_show_ops_removed: usize,
    pub forms_changed: usize,
    pub changed_page_indices: Vec<i32>,
    pub input: PageFacts,
    pub output: PageFacts,
}

#[derive(Deserialize)]
pub struct BackgroundCorpus {
    pub schema: String,
    pub render_scale: f64,
    pub ink_threshold: u8,
    pub cases: Vec<BackgroundCase>,
}

#[derive(Deserialize)]
pub struct BackgroundCase {
    pub name: String,
    pub page_count: usize,
    pub page_rect: Vec<f64>,
    pub base_pdf_b64: String,
    pub rects: Vec<Vec<f64>>,
    pub free_fills: Vec<Vec<i64>>,
    #[serde(default)]
    pub sampler_fills: Option<Vec<Vec<i64>>>,
    pub expected_input: PageFacts,
    pub expected_output: PageFacts,
}

#[derive(Deserialize)]
pub struct PageFacts {
    pub pages: Vec<PageFact>,
}

// --- Phase 7R detect / image_route corpora ------------------------------------

#[derive(Deserialize)]
pub struct DetectCorpus {
    pub schema: String,
    pub cases: Vec<DetectCase>,
}

#[derive(Deserialize)]
pub struct DetectCase {
    pub name: String,
    pub page_rect: Vec<f64>,
    pub input_pdf_b64: String,
    pub has_large: bool,
    pub tiled: bool,
    pub primary_xref: Option<i32>,
    pub primary_rect: Option<Vec<f64>>,
}

#[derive(Deserialize)]
pub struct ImageRouteCorpus {
    pub schema: String,
    pub render_scale: f64,
    pub ink_threshold: u8,
    pub cases: Vec<ImageRouteCase>,
}

#[derive(Deserialize)]
pub struct ImageRouteCase {
    pub name: String,
    pub page_rect: Vec<f64>,
    pub input_pdf_b64: String,
    pub item_bboxes: Vec<Vec<f64>>,
    pub has_large: bool,
    pub primary_xref: Option<i32>,
    pub primary_rect: Option<Vec<f64>>,
    pub changed: bool,
    pub rewritten_b64: Option<String>,
    pub expected_input: PageFacts,
    pub expected_output: PageFacts,
}

#[derive(Deserialize, Clone, Debug)]
pub struct PageFact {
    pub words: usize,
    pub ink_ratio: f64,
}

// --- Phase 7R-4 stage corpus ----------------------------------------------------

#[derive(Deserialize)]
pub struct StageCorpus {
    pub schema: String,
    pub render_scale: f64,
    pub ink_threshold: u8,
    pub cases: Vec<StageCase>,
}

#[derive(Deserialize)]
pub struct StageCase {
    pub name: String,
    pub source_pdf_b64: String,
    pub page_rect: Vec<f64>,
    pub translated_pages: std::collections::BTreeMap<i32, Vec<rendering_writer::background::redaction::RedactionItem>>,
    pub redaction_strategy: Option<String>,
    pub precleaned_page_indices: Vec<i32>,
    pub toc_entries: usize,
    #[serde(default)]
    pub toc: Vec<StageTocEntry>,
    pub per_page_diagnostics: Vec<Option<RedactionDiagnostics>>,
    pub expected_input: PageFacts,
    pub expected_output: PageFacts,
}

#[derive(Deserialize, Debug, PartialEq)]
pub struct StageTocEntry {
    pub level: i64,
    pub title: String,
    pub page: i64,
}

// --- Phase 7R-2 redaction corpus -------------------------------------------------

#[derive(Deserialize)]
pub struct RedactionCorpus {
    pub schema: String,
    pub render_scale: f64,
    pub ink_threshold: u8,
    pub cases: Vec<RedactionCase>,
}

#[derive(Deserialize)]
pub struct RedactionCase {
    pub name: String,
    pub page_rect: Vec<f64>,
    pub input_pdf_b64: String,
    pub items: Vec<rendering_writer::background::redaction::RedactionItem>,
    pub strategy: Option<String>,
    pub cover_only: bool,
    pub expected_diagnostics: RedactionDiagnostics,
    pub expected_input: PageFacts,
    pub expected_output: PageFacts,
}

#[derive(Deserialize, PartialEq, Debug)]
pub struct RedactionDiagnostics {
    pub items: usize,
    pub raw_removable_rects: usize,
    pub merged_removable_rects: usize,
    pub cover_rects: usize,
    pub fast_page_cover_only: bool,
    pub item_fast_cover_count: usize,
    pub route: String,
    pub strategy: String,
    pub uses_pymupdf_redaction: bool,
    pub legacy_pdf_write_reason: String,
    pub visual_profile_cover_rects: usize,
    pub auto_text_cleanup_math_protected: bool,
    pub auto_text_cleanup_items_skipped: usize,
}

fn load_corpus() -> &'static WriteCorpus {
    static CORPUS: OnceLock<WriteCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../write_corpus.json");
        serde_json::from_str(raw).expect("failed to parse write_corpus.json")
    })
}

pub fn corpus() -> &'static WriteCorpus {
    load_corpus()
}

fn load_background_corpus() -> &'static BackgroundCorpus {
    static CORPUS: OnceLock<BackgroundCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../background_corpus.json");
        serde_json::from_str(raw).expect("failed to parse background_corpus.json")
    })
}

pub fn background_corpus() -> &'static BackgroundCorpus {
    load_background_corpus()
}

fn load_detect_corpus() -> &'static DetectCorpus {
    static CORPUS: OnceLock<DetectCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../detect_corpus.json");
        serde_json::from_str(raw).expect("failed to parse detect_corpus.json")
    })
}

pub fn detect_corpus() -> &'static DetectCorpus {
    load_detect_corpus()
}

fn load_image_route_corpus() -> &'static ImageRouteCorpus {
    static CORPUS: OnceLock<ImageRouteCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../image_route_corpus.json");
        serde_json::from_str(raw).expect("failed to parse image_route_corpus.json")
    })
}

pub fn image_route_corpus() -> &'static ImageRouteCorpus {
    load_image_route_corpus()
}

fn load_redaction_corpus() -> &'static RedactionCorpus {
    static CORPUS: OnceLock<RedactionCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../redaction_corpus.json");
        serde_json::from_str(raw).expect("failed to parse redaction_corpus.json")
    })
}

pub fn redaction_corpus() -> &'static RedactionCorpus {
    load_redaction_corpus()
}

fn load_stage_corpus() -> &'static StageCorpus {
    static CORPUS: OnceLock<StageCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../stage_corpus.json");
        serde_json::from_str(raw).expect("failed to parse stage_corpus.json")
    })
}

pub fn stage_corpus() -> &'static StageCorpus {
    load_stage_corpus()
}

// --- Phase 7R-6 vector_text corpus ---------------------------------------------

#[derive(Deserialize)]
pub struct VectorTextCorpus {
    pub schema: String,
    pub cases: Vec<VectorTextCase>,
}

#[derive(Deserialize)]
pub struct VectorTextCase {
    pub name: String,
    pub page_rect: Vec<f64>,
    pub input_pdf_b64: String,
    pub target_rects: Vec<Vec<f64>>,
    pub expected_rects: Vec<Vec<f64>>,
}

fn load_vector_text_corpus() -> &'static VectorTextCorpus {
    static CORPUS: OnceLock<VectorTextCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../vector_text_corpus.json");
        serde_json::from_str(raw).expect("failed to parse vector_text_corpus.json")
    })
}

pub fn vector_text_corpus() -> &'static VectorTextCorpus {
    load_vector_text_corpus()
}

// --- Phase 7R-6 formula_guard corpus -------------------------------------------

#[derive(Deserialize)]
pub struct FormulaGuardCorpus {
    pub schema: String,
    pub cases: Vec<FormulaGuardCase>,
}

#[derive(Deserialize)]
pub struct FormulaGuardCase {
    pub name: String,
    pub translated_items: Vec<rendering_writer::background::redaction::RedactionItem>,
    pub redaction_items: Vec<rendering_writer::background::redaction::RedactionItem>,
    pub expected: Vec<rendering_writer::background::redaction::RedactionItem>,
}

fn load_formula_guard_corpus() -> &'static FormulaGuardCorpus {
    static CORPUS: OnceLock<FormulaGuardCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../formula_guard_corpus.json");
        serde_json::from_str(raw).expect("failed to parse formula_guard_corpus.json")
    })
}

pub fn formula_guard_corpus() -> &'static FormulaGuardCorpus {
    load_formula_guard_corpus()
}

pub fn decode(b64: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(b64.as_bytes())
        .unwrap_or_else(|e| panic!("base64 decode failed: {e}"))
}

/// Corpus `page_rects` (string keys, PDF user-space rects) → strip API form.
pub fn rect_map(map: &HashMap<String, Vec<Vec<f64>>>) -> HashMap<i32, Vec<RectTuple>> {
    map.iter()
        .map(|(k, v)| {
            let idx: i32 = k.parse().unwrap_or_else(|e| panic!("bad page key {k}: {e}"));
            let rects = v
                .iter()
                .map(|r| [r[0], r[1], r[2], r[3]])
                .collect::<Vec<RectTuple>>();
            (idx, rects)
        })
        .collect()
}

// --- measurement (mirrors gen_write_corpus.py page_facts) --------------------

/// Per-page word count via mupdf-rs `Page::words` (the fitz-vs-mupdf-rs
/// extraction-path difference is what WORD_COUNT_TOLERANCE covers).
pub fn page_words(doc: &Document, idx: i32) -> usize {
    let page = doc.load_page(idx).unwrap_or_else(|e| panic!("load_page {idx}: {e}"));
    let options = TextExtractOptions {
        flags: TextPageFlags::PRESERVE_LIGATURES,
    };
    page.words(options).unwrap_or_else(|e| panic!("words p{idx}: {e}")).len()
}

/// Ink ratio: fraction of gray-render samples below `ink_threshold`, matching
/// `gen_write_corpus.py`'s `ink_ratio` (full-page pixmap at `render_scale`).
pub fn page_ink_ratio(doc: &Document, idx: i32, scale: f32, ink_threshold: u8) -> f64 {
    let px = render_page_clip_gray(doc, idx, None, scale)
        .unwrap_or_else(|e| panic!("render p{idx}: {e}"));
    let total = (px.width as usize).saturating_mul(px.height as usize);
    if total == 0 {
        return 0.0;
    }
    let dark = px.samples.iter().filter(|&&b| b < ink_threshold).count();
    dark as f64 / total as f64
}

/// Measure all pages of `doc` into facts (the same shape as the corpus).
pub fn measure_pages(
    doc: &Document,
    page_count: usize,
    scale: f32,
    ink_threshold: u8,
) -> Vec<PageFact> {
    (0..page_count as i32)
        .map(|idx| PageFact {
            words: page_words(doc, idx),
            ink_ratio: page_ink_ratio(doc, idx, scale, ink_threshold),
        })
        .collect()
}

pub fn assert_page_facts(actual: &[PageFact], expected: &[PageFact], label: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: page fact count mismatch: actual={actual:?}, expected={expected:?}"
    );
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let rel = (a.words as f64 - e.words as f64).abs() / (e.words.max(1) as f64);
        assert!(
            rel <= WORD_COUNT_TOLERANCE,
            "{label} p{i}: words divergence actual={}, expected={}, rel={rel:.3} > {WORD_COUNT_TOLERANCE}",
            a.words,
            e.words,
        );
        let ink_diff = (a.ink_ratio - e.ink_ratio).abs();
        assert!(
            ink_diff <= INK_RATIO_TOLERANCE,
            "{label} p{i}: ink_ratio divergence actual={:.6}, expected={:.6}, diff={ink_diff:.6} > {INK_RATIO_TOLERANCE}",
            a.ink_ratio,
            e.ink_ratio,
        );
    }
}
