[package]
name = "rendering_orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
mupdf = { version = "0.8", default-features = false, features = ["base14-fonts"] }
rendering_core = { path = "../rendering_core" }
rendering_output = { path = "../rendering_output" }
rendering_reader = { path = "../rendering_reader" }
rendering_writer = { path = "../rendering_writer" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }

[[bin]]
name = "render_rs"
path = "src/main.rs"
