//! D3 bridge-contract strict gate.
//!
//! Replays `tests/contract_corpus.json` (generated by
//! `rendering_writer/differential/gen_contract_corpus.py`, which runs the REAL
//! production `build_bundle` + `_page_spec_to_dict` /
//! `render_page_spec_to_bridge` on a synthetic two-page PDF). For every bridge
//! boundary the corpus records the payload AND its portable shape tree
//! (serialized from the Python TypedDict in `contracts/bridge_shapes.py`), so
//! this test never duplicates the shape definitions.
//!
//! Two guarantees per case:
//!   1. `validate_strict` — a generic `deny_unknown_fields` replica (closed
//!      shapes reject undeclared keys; `open` shapes mirror serde's tolerance) —
//!      accepts the payload against the recorded shape. Catches producer key
//!      drift the lenient serde DTOs would silently swallow.
//!   2. the production lenient DTO deserializes the same payload, proving the
//!      strict schema and the lenient path agree on every fixture.

use std::collections::{BTreeMap, HashMap};

use rendering_orchestrator::bundle::RenderBundle;
use rendering_output::dto::RenderPageSpec as EmitterPageSpec;
use rendering_writer::background::redaction::page_specs::RenderPageSpec as RedactionPageSpec;
use rendering_writer::background::redaction::RedactionItem;
use serde::Deserialize;

#[derive(Debug, Clone)]
enum StrictSchema {
    Obj {
        fields: HashMap<String, StrictSchema>,
        required: Vec<String>,
        open: bool,
    },
    Arr(Box<StrictSchema>),
    Map(Box<StrictSchema>),
    Any,
}

impl StrictSchema {
    fn from_json(value: &serde_json::Value) -> StrictSchema {
        let obj = value.as_object().expect("schema node must be an object");
        match obj.get("type").and_then(|t| t.as_str()) {
            Some("any") => StrictSchema::Any,
            Some("arr") => StrictSchema::Arr(Box::new(StrictSchema::from_json(
                obj.get("elem").expect("arr node has elem"),
            ))),
            Some("map") => StrictSchema::Map(Box::new(StrictSchema::from_json(
                obj.get("value").expect("map node has value"),
            ))),
            Some("obj") => {
                let fields = obj
                    .get("fields")
                    .and_then(|f| f.as_object())
                    .expect("obj node has fields")
                    .iter()
                    .map(|(key, sub)| (key.clone(), StrictSchema::from_json(sub)))
                    .collect();
                let required = obj
                    .get("required")
                    .and_then(|r| r.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|key| key.as_str().map(str::to_string))
                            .collect()
                    })
                    .unwrap_or_default();
                let open = obj
                    .get("open")
                    .and_then(|flag| flag.as_bool())
                    .unwrap_or(false);
                StrictSchema::Obj {
                    fields,
                    required,
                    open,
                }
            }
            other => panic!("unknown schema node type: {other:?}"),
        }
    }
}

fn validate_strict(value: &serde_json::Value, schema: &StrictSchema) -> Result<(), String> {
    match schema {
        StrictSchema::Any => Ok(()),
        StrictSchema::Map(value_schema) => {
            let obj = value
                .as_object()
                .ok_or_else(|| format!("expected object, got {value}"))?;
            for (key, item) in obj {
                validate_strict(item, value_schema).map_err(|e| format!("{key}: {e}"))?;
            }
            Ok(())
        }
        StrictSchema::Arr(elem) => {
            let items = value
                .as_array()
                .ok_or_else(|| format!("expected array, got {value}"))?;
            for (index, item) in items.iter().enumerate() {
                validate_strict(item, elem).map_err(|e| format!("[{index}] {e}"))?;
            }
            Ok(())
        }
        StrictSchema::Obj {
            fields,
            required,
            open,
        } => {
            let obj = value
                .as_object()
                .ok_or_else(|| format!("expected object, got {value}"))?;
            for key in required {
                if !obj.contains_key(key) {
                    return Err(format!("missing required key {key:?}"));
                }
            }
            if !*open {
                for key in obj.keys() {
                    if !fields.contains_key(key) {
                        return Err(format!("unexpected key {key:?}"));
                    }
                }
            }
            for (key, field_schema) in fields {
                if let Some(sub) = obj.get(key) {
                    validate_strict(sub, field_schema).map_err(|e| format!("{key}: {e}"))?;
                }
            }
            Ok(())
        }
    }
}

#[derive(Deserialize)]
struct ContractCorpus {
    schema: String,
    cases: Vec<ContractCase>,
}

#[derive(Deserialize)]
struct ContractCase {
    name: String,
    shape: serde_json::Value,
    value: serde_json::Value,
}

fn lenient_decode(boundary: &str, value: &serde_json::Value) -> Result<(), String> {
    match boundary {
        "emitter_page_specs" => {
            let _: Vec<EmitterPageSpec> =
                serde_json::from_value(value.clone()).map_err(|e| e.to_string())?;
        }
        "redaction_page_specs" => {
            let _: Vec<RedactionPageSpec> =
                serde_json::from_value(value.clone()).map_err(|e| e.to_string())?;
        }
        "translated_pages" => {
            let _: BTreeMap<i32, Vec<RedactionItem>> =
                serde_json::from_value(value.clone()).map_err(|e| e.to_string())?;
        }
        "fill_map" => {
            let _: HashMap<String, [f64; 3]> =
                serde_json::from_value(value.clone()).map_err(|e| e.to_string())?;
        }
        "precleaned_page_indices" => {
            let _: Vec<i32> = serde_json::from_value(value.clone()).map_err(|e| e.to_string())?;
        }
        "render_bundle" => {
            let _: RenderBundle =
                serde_json::from_value(value.clone()).map_err(|e| e.to_string())?;
        }
        other => return Err(format!("unknown boundary {other}")),
    }
    Ok(())
}

#[test]
fn strict_and_lenient_agree_on_contract_corpus() {
    let raw = include_str!("contract_corpus.json");
    let corpus: ContractCorpus = serde_json::from_str(raw).expect("parse contract_corpus.json");
    assert_eq!(corpus.schema, "retainpdf_contract_corpus_v1");
    assert_eq!(corpus.cases.len(), 6, "one case per bridge boundary");
    for case in &corpus.cases {
        let schema = StrictSchema::from_json(&case.shape);
        validate_strict(&case.value, &schema)
            .unwrap_or_else(|e| panic!("{}: strict gate rejected the fixture: {e}", case.name));
        lenient_decode(&case.name, &case.value).unwrap_or_else(|e| {
            panic!(
                "{}: production lenient DTO rejected the fixture: {e}",
                case.name
            )
        });
    }
}
