//! Shared support for the rendering_reader integration tests.
//!
//! Loads `tests/golden_pdf_corpus.json` (generated by
//! `differential/gen_golden_pdf_corpus.py`) into lightweight serde DTOs and
//! provides float/geometry/vector comparison helpers for the achievable fields
//! the mupdf-rs reader can reproduce.

#![allow(dead_code)]

use std::collections::HashMap;
use std::path::Path;
use std::sync::OnceLock;

use rendering_core::page::PageSnapshot;
use rendering_core::profile::{ImageBackgroundProfile, PageGeometryProfile, VectorLayerProfile};
use serde::Deserialize;

// --- corpus loading ----------------------------------------------------------

#[derive(Deserialize)]
pub struct GoldenPdfCorpus {
    pub schema: String,
    pub background_threshold: f64,
    pub pdfs: HashMap<String, PdfEntry>,
}

#[derive(Deserialize)]
pub struct PdfEntry {
    pub category: String,
    pub page_count: i64,
    pub pages: HashMap<String, PageExpected>,
}

#[derive(Deserialize)]
pub struct PageExpected {
    pub snapshot: PageSnapshotDto,
    pub expected_profile: ProfileDto,
}

fn load_corpus() -> &'static GoldenPdfCorpus {
    static CORPUS: OnceLock<GoldenPdfCorpus> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let raw = include_str!("../golden_pdf_corpus.json");
        serde_json::from_str(raw).expect("failed to parse golden_pdf_corpus.json")
    })
}

pub fn corpus() -> &'static GoldenPdfCorpus {
    load_corpus()
}

/// Resolve the repo root from this crate (backend/rendering_reader/../..).
pub fn repo_root() -> &'static Path {
    static ROOT: OnceLock<std::path::PathBuf> = OnceLock::new();
    ROOT.get_or_init(|| {
        let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
        manifest
            .join("..")
            .join("..")
            .canonicalize()
            .expect("failed to canonicalize repo root")
    })
}

// --- snapshot / profile DTOs (mirror corpus JSON) ----------------------------

#[derive(Deserialize)]
pub struct TextTraceDto {
    #[serde(default, rename = "type")]
    pub trace_type: i64,
    #[serde(default)]
    pub opacity: f64,
}

#[derive(Deserialize)]
pub struct ImageInfoDto {
    #[serde(default)]
    pub xref: i64,
    #[serde(default)]
    pub bbox: [f64; 4],
}

#[derive(Deserialize)]
pub struct PageSnapshotDto {
    pub number: i64,
    pub rotation: i64,
    pub rect: [f64; 4],
    pub cropbox: [f64; 4],
    #[serde(default)]
    pub text_traces: Vec<TextTraceDto>,
    #[serde(default)]
    pub word_count: i64,
    #[serde(default)]
    pub drawing_count: i64,
    #[serde(default)]
    pub image_infos: Vec<ImageInfoDto>,
    #[serde(default)]
    pub image_entries: Vec<i64>,
    #[serde(default)]
    pub image_rects: HashMap<String, Vec<[f64; 4]>>,
}

#[derive(Deserialize)]
pub struct GeometryDto {
    pub page_index: i64,
    pub width_pt: f64,
    pub height_pt: f64,
    pub rotation: i64,
    pub cropbox: [f64; 4],
}

#[derive(Deserialize)]
pub struct VectorLayerDto {
    pub drawing_count: i64,
    pub vector_heavy: bool,
    pub cover_only_preferred: bool,
}

#[derive(Deserialize)]
pub struct TextLayerDto {
    pub visible_traces: i64,
    pub hidden_traces: i64,
    pub has_visible_text: bool,
    pub has_hidden_text: bool,
    pub editable: bool,
}

#[derive(Deserialize)]
pub struct ImageBackgroundDto {
    pub has_large_background: bool,
    pub coverage_ratio: f64,
    pub xref: Option<i64>,
    pub bbox: Option<[f64; 4]>,
}

#[derive(Deserialize)]
pub struct OcrBlocksDto {
    pub block_count: i64,
    pub valid_bbox_count: i64,
    pub total_bbox_area: f64,
    pub page_area_ratio: f64,
}

#[derive(Deserialize)]
pub struct ProfileDto {
    pub geometry: GeometryDto,
    pub text_layer: TextLayerDto,
    pub image_background: ImageBackgroundDto,
    pub vector_layer: VectorLayerDto,
    pub ocr_blocks: OcrBlocksDto,
    pub kind: String,
}

// --- comparison helpers ------------------------------------------------------

pub fn assert_close_f64(actual: f64, expected: f64) {
    let tol = 1e-6 * expected.abs().max(1.0);
    assert!(
        (actual - expected).abs() <= tol,
        "float mismatch: actual={actual}, expected={expected}, tol={tol}"
    );
}

pub fn assert_close_f64_slice(actual: &[f64], expected: &[f64]) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "slice length mismatch: actual={actual:?}, expected={expected:?}"
    );
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let tol = 1e-6 * e.abs().max(1.0);
        assert!(
            (a - e).abs() <= tol,
            "float mismatch at index {i}: actual={a}, expected={e}, tol={tol}"
        );
    }
}

pub fn assert_close_geometry(a: &PageGeometryProfile, b: &GeometryDto) {
    assert_eq!(a.page_index, b.page_index, "page_index");
    assert_eq!(a.rotation, b.rotation, "rotation");
    assert_close_f64(a.width_pt, b.width_pt);
    assert_close_f64(a.height_pt, b.height_pt);
    assert_close_f64_slice(&a.cropbox, &b.cropbox);
}

pub fn assert_close_vector_layer(a: &VectorLayerProfile, b: &VectorLayerDto) {
    assert_eq!(a.drawing_count, b.drawing_count, "drawing_count");
    assert_eq!(a.vector_heavy, b.vector_heavy, "vector_heavy");
    assert_eq!(a.cover_only_preferred, b.cover_only_preferred, "cover_only_preferred");
}

/// Image-background parity (Inc 3). `has_large_background` / `coverage_ratio`
/// depend only on the placement union, which the aggregate `image_rects` fill
/// reproduces; `xref` / `bbox` are intentionally NOT compared — mupdf-rs cannot
/// attribute placements to xrefs, so the aggregate fill diverges per-xref (the
/// documented Inc 3 tie).
pub fn assert_close_image_background(a: &ImageBackgroundProfile, b: &ImageBackgroundDto) {
    assert_eq!(a.has_large_background, b.has_large_background, "has_large_background");
    assert_close_f64(a.coverage_ratio, b.coverage_ratio);
}

/// Word-count tolerance vs fitz. fitz `get_text("words")` extracts via
/// `fz_stext_words` (PRESERVE_LIGATURES + PyMuPDF's glyph-to-Unicode mapping);
/// mupdf-rs `words()` calls `fz_page_words` (different path, maps ligature
/// glyphs ﬁ/ﬂ to U+FFFD and merges neighbors). Divergence measured on the
/// golden corpus: 25/42 pages differ, max 5.4%. 10% headroom covers it without
/// masking regressions.
const WORD_COUNT_TOLERANCE: f64 = 0.10;

/// Assert the reader-produced snapshot matches the corpus snapshot on the
/// achievable fields (number, rotation, rect, cropbox, word_count,
/// drawing_count, image_entries) and that the Phase-5 placeholder fields are in
/// their deterministic reader-contract state (empty text_traces, aggregate
/// image_rects, zero image bboxes).
pub fn assert_snapshot_achievable(actual: &PageSnapshot, expected: &PageSnapshotDto) {
    assert_eq!(actual.number, expected.number, "number");
    assert_eq!(actual.rotation, expected.rotation, "rotation");
    assert_close_f64_slice(&rect_slice(actual), &expected.rect);
    assert_close_f64_slice(&cropbox_slice(actual), &expected.cropbox);
    let rel = (actual.word_count - expected.word_count).abs() as f64
        / (expected.word_count.max(1) as f64);
    assert!(
        rel <= WORD_COUNT_TOLERANCE,
        "word_count divergence (fitz vs mupdf-rs extraction path): \
         actual={}, expected={}, rel={rel:.3} > {WORD_COUNT_TOLERANCE}",
        actual.word_count,
        expected.word_count,
    );
    assert_eq!(actual.drawing_count, expected.drawing_count, "drawing_count");

    let mut actual_xrefs: Vec<i64> = actual.image_entries.iter().copied().collect();
    let mut expected_xrefs = expected.image_entries.clone();
    actual_xrefs.sort_unstable();
    expected_xrefs.sort_unstable();
    assert_eq!(actual_xrefs, expected_xrefs, "image_entries");

    assert!(
        actual.text_traces.is_empty(),
        "Phase 5: text_traces must be empty (no mupdf-rs texttrace API)"
    );
    // Inc 3: image_rects carries the aggregate placement set — every real xref
    // maps to the full placement list (mupdf-rs exposes no placement→xref
    // association). The keys must match the positive image_entries; exact
    // values are pinned in `image_rects_diff.rs`.
    let mut actual_keys: Vec<i64> = actual.image_rects.keys().copied().collect();
    actual_keys.sort_unstable();
    let mut expected_keys: Vec<i64> = expected
        .image_entries
        .iter()
        .copied()
        .filter(|&x| x > 0)
        .collect();
    expected_keys.sort_unstable();
    expected_keys.dedup();
    assert_eq!(
        actual_keys, expected_keys,
        "image_rects keys must match the distinct positive image_entries"
    );
    for info in &actual.image_infos {
        assert_eq!(info.bbox.x0, 0.0, "image bbox must be zero (Phase 5)");
        assert_eq!(info.bbox.y0, 0.0, "image bbox must be zero (Phase 5)");
        assert_eq!(info.bbox.x1, 0.0, "image bbox must be zero (Phase 5)");
        assert_eq!(info.bbox.y1, 0.0, "image bbox must be zero (Phase 5)");
    }
}

fn rect_slice(s: &PageSnapshot) -> [f64; 4] {
    [s.rect.x0, s.rect.y0, s.rect.x1, s.rect.y1]
}

fn cropbox_slice(s: &PageSnapshot) -> [f64; 4] {
    [s.cropbox.x0, s.cropbox.y0, s.cropbox.x1, s.cropbox.y1]
}
