//! Phase 5D-7 background-fill differential: mupdf-rs `background` fill pipeline
//! vs production `source/background/fill.py`.
//!
//! Replays `tests/background_corpus.json` (generated by
//! `differential/gen_background_corpus.py`, which runs the REAL production
//! `sample_local_background_fill` / `LocalBackgroundSampler.build` /
//! `draw_white_covers`). For each case:
//!   1. open the embedded base PDF and measure input facts,
//!   2. recompute each rect's fill via the ported free path and the batched
//!      sampler path (when the corpus recorded sampler fills), asserting each
//!      channel within ±2/255 of the fitz-computed value,
//!   3. draw the white covers onto a mutable PdfDocument, save, reopen, and
//!      assert output words (±10% rel) and ink ratio (±0.02 abs).

use std::fs;
use std::path::Path;

use mupdf::Document;
use rendering_core::source_cleanup::hit_test::RectTuple;
use rendering_reader::render::render_page_clip_rgb;
use rendering_writer::background::fill::{
    build_local_background_sampler, draw_white_covers, sample_local_background_fill, RgbPixmap,
};
use rendering_writer::save::{delete_trailer_id, save_atomic};

mod common;
use common::{
    assert_page_facts, background_corpus, decode, measure_pages, BackgroundCase,
};

/// Write `bytes` to a fresh temp file inside `dir` and return its path.
fn write_input(dir: &Path, name: &str, bytes: &[u8]) -> std::path::PathBuf {
    let path = dir.join(name);
    fs::write(&path, bytes).expect("write input pdf");
    path
}

/// Python `quantize`: `int(round(c * 255))` with ties-to-even rounding.
fn quantize_fill(fill: [f64; 3]) -> [i64; 3] {
    [
        (fill[0] * 255.0).round_ties_even() as i64,
        (fill[1] * 255.0).round_ties_even() as i64,
        (fill[2] * 255.0).round_ties_even() as i64,
    ]
}

fn assert_fills(actual: &[[i64; 3]], expected: &[Vec<i64>], label: &str) {
    assert_eq!(actual.len(), expected.len(), "{label}: fill count");
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_eq!(e.len(), 3, "{label} rect {i}: expected fill dim");
        for (ch, (a_ch, e_ch)) in a.iter().zip(e.iter()).enumerate() {
            let diff = (a_ch - e_ch).abs();
            assert!(
                diff <= 2,
                "{label} rect {i} ch{ch}: fill divergence actual={a_ch} expected={e_ch} diff={diff} > 2",
            );
        }
    }
}

fn replay_case(case: &BackgroundCase, scale: f32, threshold: u8) {
    let dir = tempfile_dir(&format!("background-{}", case.name));
    let in_path = write_input(&dir, "in.pdf", &decode(&case.base_pdf_b64));

    // Measure the pristine base PDF (fitz vs mupdf-rs semantic equivalence).
    let doc = Document::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
    let input_facts = measure_pages(&doc, case.page_count, scale, threshold);
    assert_page_facts(
        &input_facts,
        &case.expected_input.pages,
        &format!("{} input", case.name),
    );

    let page_rect: RectTuple = [
        case.page_rect[0],
        case.page_rect[1],
        case.page_rect[2],
        case.page_rect[3],
    ];
    let rects: Vec<RectTuple> = case
        .rects
        .iter()
        .map(|r| [r[0], r[1], r[2], r[3]])
        .collect();

    // RGB clip renderer in page space; reads the pristine `doc` throughout so
    // all fills come from the uncovered page (same as the corpus generator).
    let render_clip = |clip: &RectTuple| -> Option<RgbPixmap> {
        let rect = mupdf::Rect::new(
            clip[0] as f32,
            clip[1] as f32,
            clip[2] as f32,
            clip[3] as f32,
        );
        render_page_clip_rgb(&doc, 0, Some(&rect), scale)
            .ok()
            .map(|px| RgbPixmap {
                width: px.width as usize,
                height: px.height as usize,
                samples: px.samples,
            })
    };

    // Free-path fills (no batched sampler).
    let free_fills: Vec<[i64; 3]> = rects
        .iter()
        .map(|r| quantize_fill(sample_local_background_fill(&page_rect, &render_clip, r, None)))
        .collect();
    assert_fills(&free_fills, &case.free_fills, &format!("{} free fills", case.name));

    // Batched sampler fills, when the corpus recorded them (>= 8 rects whose
    // union clip stays within 35% of the page).
    if let Some(expected_sampler) = &case.sampler_fills {
        let sampler = build_local_background_sampler(&page_rect, &rects, &render_clip)
            .unwrap_or_else(|| panic!("{} build sampler", case.name));
        let sampler_fills: Vec<[i64; 3]> = rects
            .iter()
            .map(|r| {
                quantize_fill(sampler.sample_local_background_fill(r).unwrap_or([1.0, 1.0, 1.0]))
            })
            .collect();
        assert_fills(
            &sampler_fills,
            expected_sampler,
            &format!("{} sampler fills", case.name),
        );
    }

    // Draw the covers on a mutable PdfDocument and measure output facts.
    let mut pdf = mupdf::pdf::PdfDocument::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open for edit: {e}", case.name));
    let mut page = pdf
        .load_pdf_page(0)
        .unwrap_or_else(|e| panic!("{} load p0: {e}", case.name));
    draw_white_covers(&mut page, &mut pdf, &page_rect, &rects, &render_clip)
        .unwrap_or_else(|e| panic!("{} draw_white_covers: {e}", case.name));

    delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
    let out_path = dir.join("out.pdf");
    save_atomic(&pdf, &out_path).unwrap_or_else(|e| panic!("{} save: {e}", case.name));

    let out_doc = Document::open(out_path.as_path())
        .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
    assert_eq!(
        out_doc.page_count().unwrap_or(0) as usize,
        case.page_count,
        "{} output page_count",
        case.name
    );
    let output_facts = measure_pages(&out_doc, case.page_count, scale, threshold);
    assert_page_facts(
        &output_facts,
        &case.expected_output.pages,
        &format!("{} output", case.name),
    );
}

#[test]
fn background_fill_replay_matches_production() {
    let corpus = background_corpus();
    assert_eq!(corpus.schema, "retainpdf_background_corpus_v1");
    assert!(!corpus.cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;

    for case in &corpus.cases {
        replay_case(case, scale, threshold);
    }
}

/// Unique temp dir per case (scoped to the OS temp dir; cleaned by the OS).
fn tempfile_dir(name: &str) -> std::path::PathBuf {
    let base = std::env::temp_dir().join(format!("rpbg-{}-{}", name, std::process::id()));
    fs::create_dir_all(&base).expect("create temp dir");
    base
}
