//! Phase 7R-1 background-image detection differential: mupdf-rs `background::detect`
//! vs production `source/background/detect.py`.
//!
//! Replays `tests/detect_corpus.json` (generated by
//! `differential/gen_detect_corpus.py`, which runs the REAL production
//! `page_has_large_background_image` / `page_has_tiled_background_images` /
//! `pick_primary_background_image`). For each case the Rust side walks the page
//! content stream (CTM at each `Do`) to reproduce the same placement rects and
//! asserts has_large / tiled / primary xref + placement rect exactly.

use std::fs;
use std::path::Path;

use mupdf::pdf::PdfDocument;
use rendering_core::source_cleanup::hit_test::RectTuple;
use rendering_writer::background::config::DETECT_PRIMARY_COVERAGE_RATIO;
use rendering_writer::background::detect::{
    page_has_large_background_image, page_has_tiled_background_images,
    pick_primary_background_image,
};

mod common;
use common::{decode, detect_corpus, DetectCase};

fn write_input(dir: &Path, name: &str, bytes: &[u8]) -> std::path::PathBuf {
    let path = dir.join(name);
    fs::write(&path, bytes).expect("write input pdf");
    path
}

fn assert_rect_eq(actual: &RectTuple, expected: &[f64], label: &str) {
    assert_eq!(actual.len(), expected.len(), "{label}: rect dim");
    for i in 0..actual.len() {
        let diff = (actual[i] - expected[i]).abs();
        assert!(
            diff <= 1e-6,
            "{label}[{i}]: actual={:?} expected={expected:?}",
            actual
        );
    }
}

fn replay_case(case: &DetectCase) {
    let dir = std::env::temp_dir().join(format!("rpdet-{}-{}", case.name, std::process::id()));
    fs::create_dir_all(&dir).expect("create temp dir");
    let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));

    let pdf = PdfDocument::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open: {e}", case.name));
    let page = pdf.load_pdf_page(0).unwrap_or_else(|e| panic!("{} load p0: {e}", case.name));
    let page_rect: RectTuple = [
        case.page_rect[0],
        case.page_rect[1],
        case.page_rect[2],
        case.page_rect[3],
    ];

    let has_large = page_has_large_background_image(&page, &page_rect)
        .unwrap_or_else(|e| panic!("{} has_large: {e}", case.name));
    assert_eq!(has_large, case.has_large, "{} has_large", case.name);

    let tiled = page_has_tiled_background_images(&page, &page_rect)
        .unwrap_or_else(|e| panic!("{} tiled: {e}", case.name));
    assert_eq!(tiled, case.tiled, "{} tiled", case.name);

    let primary = pick_primary_background_image(&page, &page_rect, DETECT_PRIMARY_COVERAGE_RATIO)
        .unwrap_or_else(|e| panic!("{} primary: {e}", case.name));
    match (&case.primary_xref, &case.primary_rect) {
        (Some(exp_xref), Some(exp_rect)) => {
            let (xref, rect) = primary
                .unwrap_or_else(|| panic!("{} expected a primary, got None", case.name));
            assert_eq!(xref, *exp_xref, "{} primary_xref", case.name);
            assert_rect_eq(&rect, exp_rect, &format!("{} primary_rect", case.name));
        }
        (None, None) => {
            assert!(primary.is_none(), "{} expected no primary, got {primary:?}", case.name);
        }
        _ => panic!("{} inconsistent corpus primary", case.name),
    }
}

#[test]
fn detect_replay_matches_production() {
    let corpus = detect_corpus();
    assert_eq!(corpus.schema, "retainpdf_detect_corpus_v1");
    assert!(!corpus.cases.is_empty());
    for case in &corpus.cases {
        replay_case(case);
    }
}
