//! Phase 7R-6 formula-guard differential: mupdf-rs `background::formula_guard`
//! vs production `policy/formula_guard.py::protect_formula_regions_in_redaction_items`.
//!
//! Replays `tests/formula_guard_corpus.json` (generated by
//! `differential/gen_formula_guard_corpus.py`, which runs the REAL production
//! function with the layout config pinned and asserts each case before
//! recording). For each case the Rust side runs the ported
//! `protect_formula_regions_in_redaction_items` on the recorded DTOs and
//! asserts the output projection (bbox, `formula_guard_fragment`,
//! `formula_guard_fragment_index`) matches the recorded projection exactly.

use rendering_writer::background::formula_guard::protect_formula_regions_in_redaction_items;
use rendering_writer::background::redaction::RedactionItem;

mod common;
use common::formula_guard_corpus;

type Projection = (Option<Vec<f64>>, bool, Option<i32>);

fn project(item: &RedactionItem) -> Projection {
    (
        item.bbox.clone(),
        item.formula_guard_fragment,
        item.formula_guard_fragment_index,
    )
}

#[test]
fn formula_guard_replay_matches_production() {
    let corpus = formula_guard_corpus();
    assert_eq!(corpus.schema, "retainpdf_formula_guard_corpus_v1");
    assert!(!corpus.cases.is_empty());
    for case in &corpus.cases {
        let actual = protect_formula_regions_in_redaction_items(
            case.redaction_items.clone(),
            &case.translated_items,
        );
        let actual_proj: Vec<Projection> = actual.iter().map(project).collect();
        let expected_proj: Vec<Projection> = case.expected.iter().map(project).collect();
        assert_eq!(actual_proj, expected_proj, "{}", case.name);
    }
}
