//! Phase 7R-1 background-image route differential: mupdf-rs
//! `background::image_route` (raw-stream FlateDecode branch) vs production
//! `source/background/image_route.py`.
//!
//! Replays `tests/image_route_corpus.json` (generated by
//! `differential/gen_image_route_corpus.py`, which runs the REAL production
//! `replace_background_image_page`). For each case the Rust side re-derives the
//! detect facts, runs the ported replacement, asserts the `changed` flag, and —
//! when changed — asserts the rewritten primary stream decodes byte-identical
//! to the production bytes. Page facts (words / ink) are compared on input and
//! output with the usual tolerances.

use std::fs;
use std::path::Path;

use mupdf::pdf::PdfDocument;
use mupdf::Document;
use rendering_core::source_cleanup::hit_test::RectTuple;
use rendering_writer::background::config::DETECT_PRIMARY_COVERAGE_RATIO;
use rendering_writer::background::detect::{
    page_has_large_background_image, pick_primary_background_image,
};
use rendering_writer::background::image_route::replace_background_image_page;
use rendering_writer::save::{delete_trailer_id, save_atomic};

mod common;
use common::{assert_page_facts, decode, image_route_corpus, measure_pages, ImageRouteCase};

fn write_input(dir: &Path, name: &str, bytes: &[u8]) -> std::path::PathBuf {
    let path = dir.join(name);
    fs::write(&path, bytes).expect("write input pdf");
    path
}

fn assert_rect_eq(actual: &RectTuple, expected: &[f64], label: &str) {
    assert_eq!(actual.len(), expected.len(), "{label}: rect dim");
    for i in 0..actual.len() {
        let diff = (actual[i] - expected[i]).abs();
        assert!(
            diff <= 1e-6,
            "{label}[{i}]: actual={:?} expected={expected:?}",
            actual
        );
    }
}

fn replay_case(case: &ImageRouteCase, scale: f32, threshold: u8) {
    let dir = std::env::temp_dir().join(format!("rpi-{}-{}", case.name, std::process::id()));
    fs::create_dir_all(&dir).expect("create temp dir");
    let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));

    // Input facts from a pristine open.
    let in_doc = Document::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
    let input_facts = measure_pages(&in_doc, 1, scale, threshold);
    assert_page_facts(&input_facts, &case.expected_input.pages, &format!("{} input", case.name));

    let page_rect: RectTuple = [
        case.page_rect[0],
        case.page_rect[1],
        case.page_rect[2],
        case.page_rect[3],
    ];
    let item_bboxes: Vec<RectTuple> = case
        .item_bboxes
        .iter()
        .map(|r| [r[0], r[1], r[2], r[3]])
        .collect();

    // Re-derive the detect facts on the pristine page.
    let mut pdf = PdfDocument::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open for edit: {e}", case.name));
    let page = pdf.load_pdf_page(0).unwrap_or_else(|e| panic!("{} load p0: {e}", case.name));
    let has_large = page_has_large_background_image(&page, &page_rect)
        .unwrap_or_else(|e| panic!("{} has_large: {e}", case.name));
    assert_eq!(has_large, case.has_large, "{} has_large", case.name);
    let primary = pick_primary_background_image(&page, &page_rect, DETECT_PRIMARY_COVERAGE_RATIO)
        .unwrap_or_else(|e| panic!("{} primary: {e}", case.name));
    match (&case.primary_xref, &case.primary_rect) {
        (Some(exp_xref), Some(exp_rect)) => {
            let (xref, rect) = primary
                .unwrap_or_else(|| panic!("{} expected a primary, got None", case.name));
            assert_eq!(xref, *exp_xref, "{} primary_xref", case.name);
            assert_rect_eq(&rect, exp_rect, &format!("{} primary_rect", case.name));
        }
        (None, None) => {
            assert!(primary.is_none(), "{} expected no primary, got {primary:?}", case.name);
        }
        _ => panic!("{} inconsistent corpus primary", case.name),
    }

    // Run the ported replacement and assert the changed flag.
    let changed = replace_background_image_page(&page, &mut pdf, &page_rect, &item_bboxes)
        .unwrap_or_else(|e| panic!("{} replace: {e}", case.name));
    assert_eq!(changed, case.changed, "{} changed", case.name);

    // Byte-identical rewritten stream (the strongest assertion).
    if changed {
        let xref = case.primary_xref.expect("changed case must record a primary xref");
        let expected = decode(case.rewritten_b64.as_deref().expect("changed case must record rewritten bytes"));
        let actual = pdf
            .xref_stream(xref)
            .unwrap_or_else(|e| panic!("{} xref_stream {xref}: {e}", case.name));
        assert_eq!(
            actual,
            expected,
            "{} rewritten stream diverges ({} bytes vs {} expected)",
            case.name,
            actual.len(),
            expected.len(),
        );
    }

    // Save, reopen, and compare output facts.
    delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
    let out_path = dir.join("out.pdf");
    save_atomic(&pdf, &out_path).unwrap_or_else(|e| panic!("{} save: {e}", case.name));
    let out_doc = Document::open(out_path.as_path())
        .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
    let output_facts = measure_pages(&out_doc, 1, scale, threshold);
    assert_page_facts(&output_facts, &case.expected_output.pages, &format!("{} output", case.name));
}

#[test]
fn image_route_replay_matches_production() {
    let corpus = image_route_corpus();
    assert_eq!(corpus.schema, "retainpdf_image_route_corpus_v1");
    assert!(!corpus.cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;
    for case in &corpus.cases {
        replay_case(case, scale, threshold);
    }
}
