//! Phase 7R-2 redaction-engine differential: mupdf-rs
//! `background::redaction::execute_redaction_flow` (auto / visual_cover /
//! visual_cover_and_remove_text routing + cover primitives + safe-direct text
//! matcher) vs production `source/cleanup/redaction_flow.py`.
//!
//! Replays `tests/redaction_corpus.json` (generated by
//! `differential/gen_redaction_corpus.py`, which runs the REAL production flow
//! on synthetic pages). For each case the Rust side runs the ported engine over
//! the pristine render-side page (text extraction + clip sampling) and the
//! edit-side page (covers + redaction annotations), asserts the exact
//! `RedactionDiagnostics`, then measures output page facts (words / ink) with
//! the usual tolerances.

use std::fs;
use std::path::Path;

use mupdf::pdf::PdfDocument;
use mupdf::Document;
use rendering_core::source_cleanup::hit_test::RectTuple;
use rendering_reader::render::render_page_clip_rgb;
use rendering_writer::background::redaction::{execute_redaction_flow, RedactionDiagnostics};
use rendering_writer::background::fill::RgbPixmap;
use rendering_writer::save::{delete_trailer_id, save_atomic};

mod common;
use common::{
    assert_page_facts, decode, measure_pages, redaction_corpus, RedactionCase, RedactionDiagnostics as ExpectedDiag,
};

fn write_input(dir: &Path, name: &str, bytes: &[u8]) -> std::path::PathBuf {
    let path = dir.join(name);
    fs::write(&path, bytes).expect("write input pdf");
    path
}

fn assert_diag_eq(actual: &RedactionDiagnostics, expected: &ExpectedDiag, label: &str) {
    assert_eq!(actual.items, expected.items, "{label}: items");
    assert_eq!(
        actual.raw_removable_rects, expected.raw_removable_rects,
        "{label}: raw_removable_rects"
    );
    assert_eq!(
        actual.merged_removable_rects, expected.merged_removable_rects,
        "{label}: merged_removable_rects"
    );
    assert_eq!(actual.cover_rects, expected.cover_rects, "{label}: cover_rects");
    assert_eq!(
        actual.fast_page_cover_only, expected.fast_page_cover_only,
        "{label}: fast_page_cover_only"
    );
    assert_eq!(
        actual.item_fast_cover_count, expected.item_fast_cover_count,
        "{label}: item_fast_cover_count"
    );
    assert_eq!(actual.route, expected.route, "{label}: route");
    assert_eq!(actual.strategy, expected.strategy, "{label}: strategy");
    assert_eq!(
        actual.uses_pymupdf_redaction, expected.uses_pymupdf_redaction,
        "{label}: uses_pymupdf_redaction"
    );
    assert_eq!(
        actual.legacy_pdf_write_reason, expected.legacy_pdf_write_reason,
        "{label}: legacy_pdf_write_reason"
    );
    assert_eq!(
        actual.visual_profile_cover_rects, expected.visual_profile_cover_rects,
        "{label}: visual_profile_cover_rects"
    );
    assert_eq!(
        actual.auto_text_cleanup_math_protected, expected.auto_text_cleanup_math_protected,
        "{label}: auto_text_cleanup_math_protected"
    );
    assert_eq!(
        actual.auto_text_cleanup_items_skipped, expected.auto_text_cleanup_items_skipped,
        "{label}: auto_text_cleanup_items_skipped"
    );
}

fn replay_case(case: &RedactionCase, scale: f32, threshold: u8) {
    let dir = std::env::temp_dir().join(format!("rpr-{}-{}", case.name, std::process::id()));
    fs::create_dir_all(&dir).expect("create temp dir");
    let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));

    // Pristine render handle: input facts, text extraction, clip sampling.
    let doc = Document::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
    let input_facts = measure_pages(&doc, 1, scale, threshold);
    assert_page_facts(&input_facts, &case.expected_input.pages, &format!("{} input", case.name));

    let render_page = doc
        .load_page(0)
        .unwrap_or_else(|e| panic!("{} load render p0: {e}", case.name));
    let render_clip = |clip: &RectTuple| -> Option<RgbPixmap> {
        let rect = mupdf::Rect::new(clip[0] as f32, clip[1] as f32, clip[2] as f32, clip[3] as f32);
        render_page_clip_rgb(&doc, 0, Some(&rect), scale)
            .ok()
            .map(|px| RgbPixmap {
                width: px.width as usize,
                height: px.height as usize,
                samples: px.samples,
            })
    };

    let page_rect: RectTuple = [
        case.page_rect[0],
        case.page_rect[1],
        case.page_rect[2],
        case.page_rect[3],
    ];

    // Edit handle: covers + redaction annotations.
    let mut pdf = PdfDocument::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open for edit: {e}", case.name));
    let mut edit_page = pdf
        .load_pdf_page(0)
        .unwrap_or_else(|e| panic!("{} load edit p0: {e}", case.name));

    let diagnostics = execute_redaction_flow(
        &render_page,
        &mut edit_page,
        &mut pdf,
        &page_rect,
        &case.items,
        &render_clip,
        case.cover_only,
        case.strategy.as_deref(),
    )
    .unwrap_or_else(|e| panic!("{} execute_redaction_flow: {e}", case.name));
    assert_diag_eq(&diagnostics, &case.expected_diagnostics, &case.name);

    // Save, reopen, and compare output facts.
    delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
    let out_path = dir.join("out.pdf");
    save_atomic(&pdf, &out_path).unwrap_or_else(|e| panic!("{} save: {e}", case.name));
    let out_doc = Document::open(out_path.as_path())
        .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
    let output_facts = measure_pages(&out_doc, 1, scale, threshold);
    assert_page_facts(&output_facts, &case.expected_output.pages, &format!("{} output", case.name));
}

#[test]
fn redaction_engine_replay_matches_production() {
    let corpus = redaction_corpus();
    assert_eq!(corpus.schema, "retainpdf_redaction_corpus_v1");
    assert!(!corpus.cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;
    for case in &corpus.cases {
        replay_case(case, scale, threshold);
    }
}

/// Phase 7R-3 gate: the full text-span matcher (block / word / whole-bbox
/// layers). Focused on the `textmatch_*` corpus cases so a matcher regression
/// is attributed precisely, independent of the broader engine replay above.
#[test]
fn redaction_text_matching_replay() {
    let corpus = redaction_corpus();
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;
    let cases: Vec<&RedactionCase> = corpus
        .cases
        .iter()
        .filter(|c| c.name.starts_with("textmatch_"))
        .collect();
    assert_eq!(
        cases.len(),
        4,
        "expected the four Phase 7R-3 matcher cases, got {}",
        cases.len()
    );
    for case in cases {
        replay_case(case, scale, threshold);
    }
}
