//! Phase 7R-4 stage differential: mupdf-rs
//! `background::stage::build_clean_background_pdf` (copy_toc + per-page
//! redaction orchestration) vs production `source/background/stage.py`.
//!
//! Replays `tests/stage_corpus.json` (generated by
//! `differential/gen_stage_corpus.py`, which runs the REAL production
//! `build_clean_background_pdf` on synthetic multi-page PDFs). For each case the
//! Rust side opens `source_doc`/`edit_pdf` from the same input bytes, runs the
//! ported stage (which calls the ported `copy_toc` and per-page redaction
//! engine with a page-aware clip sampler), asserts the exact per-page
//! `RedactionDiagnostics` + `toc_entries`, saves optimized, then measures the
//! output page facts (words / ink) and the output outline list.

use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::path::Path;

use mupdf::pdf::PdfDocument;
use mupdf::{Document, Error, Outline};
use rendering_core::source_cleanup::hit_test::RectTuple;
use rendering_reader::render::render_page_clip_rgb;
use rendering_writer::background::redaction::{RedactionDiagnostics, RedactionItem};
use rendering_writer::background::fill::RgbPixmap;
use rendering_writer::background::stage::build_clean_background_pdf;
use rendering_writer::save::{delete_trailer_id, save_optimized};

mod common;
use common::{
    assert_page_facts, decode, measure_pages, stage_corpus, RedactionDiagnostics as ExpectedDiag, StageCase,
    StageTocEntry,
};

fn write_input(dir: &Path, name: &str, bytes: &[u8]) -> std::path::PathBuf {
    let path = dir.join(name);
    fs::write(&path, bytes).expect("write input pdf");
    path
}

fn assert_diag_eq(actual: &RedactionDiagnostics, expected: &ExpectedDiag, label: &str) {
    assert_eq!(actual.items, expected.items, "{label}: items");
    assert_eq!(
        actual.raw_removable_rects, expected.raw_removable_rects,
        "{label}: raw_removable_rects"
    );
    assert_eq!(
        actual.merged_removable_rects, expected.merged_removable_rects,
        "{label}: merged_removable_rects"
    );
    assert_eq!(actual.cover_rects, expected.cover_rects, "{label}: cover_rects");
    assert_eq!(
        actual.fast_page_cover_only, expected.fast_page_cover_only,
        "{label}: fast_page_cover_only"
    );
    assert_eq!(
        actual.item_fast_cover_count, expected.item_fast_cover_count,
        "{label}: item_fast_cover_count"
    );
    assert_eq!(actual.route, expected.route, "{label}: route");
    assert_eq!(actual.strategy, expected.strategy, "{label}: strategy");
    assert_eq!(
        actual.uses_pymupdf_redaction, expected.uses_pymupdf_redaction,
        "{label}: uses_pymupdf_redaction"
    );
    assert_eq!(
        actual.legacy_pdf_write_reason, expected.legacy_pdf_write_reason,
        "{label}: legacy_pdf_write_reason"
    );
    assert_eq!(
        actual.visual_profile_cover_rects, expected.visual_profile_cover_rects,
        "{label}: visual_profile_cover_rects"
    );
    assert_eq!(
        actual.auto_text_cleanup_math_protected, expected.auto_text_cleanup_math_protected,
        "{label}: auto_text_cleanup_math_protected"
    );
    assert_eq!(
        actual.auto_text_cleanup_items_skipped, expected.auto_text_cleanup_items_skipped,
        "{label}: auto_text_cleanup_items_skipped"
    );
}

/// Flatten the output outline tree into `[level, title, page+1]` triples,
/// matching fitz `get_toc()`'s 1-based pages (mirrors `toc.rs::flatten_outline`).
fn flatten_outlines(outlines: &[Outline], level: i64, out: &mut Vec<StageTocEntry>) {
    for outline in outlines {
        if let Some(dest) = &outline.dest {
            out.push(StageTocEntry {
                level,
                title: outline.title.clone(),
                page: dest.loc.page_number as i64 + 1,
            });
        }
        flatten_outlines(&outline.down, level + 1, out);
    }
}

fn replay_case(case: &StageCase, scale: f32, threshold: u8) {
    let dir = std::env::temp_dir().join(format!("rps-{}-{}", case.name, std::process::id()));
    fs::create_dir_all(&dir).expect("create temp dir");
    let in_path = write_input(&dir, "in.pdf", &decode(&case.source_pdf_b64));

    let doc = Document::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
    let page_count = doc.page_count().unwrap_or_else(|e| panic!("{} page_count: {e}", case.name)) as usize;
    let input_facts = measure_pages(&doc, page_count, scale, threshold);
    assert_page_facts(&input_facts, &case.expected_input.pages, &format!("{} input", case.name));

    let page_rect: RectTuple = [
        case.page_rect[0],
        case.page_rect[1],
        case.page_rect[2],
        case.page_rect[3],
    ];

    let render_clip = |page_index: i32, clip: &RectTuple| -> Option<RgbPixmap> {
        let rect = mupdf::Rect::new(clip[0] as f32, clip[1] as f32, clip[2] as f32, clip[3] as f32);
        render_page_clip_rgb(&doc, page_index, Some(&rect), scale)
            .ok()
            .map(|px| RgbPixmap {
                width: px.width as usize,
                height: px.height as usize,
                samples: px.samples,
            })
    };

    let mut pdf = PdfDocument::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open for edit: {e}", case.name));

    let translated_pages: BTreeMap<i32, Vec<RedactionItem>> = case.translated_pages.clone();
    let precleaned: HashSet<i32> = case.precleaned_page_indices.iter().copied().collect();

    let outcome = build_clean_background_pdf(
        &doc,
        &mut pdf,
        &page_rect,
        &translated_pages,
        case.redaction_strategy.as_deref(),
        &precleaned,
        &render_clip,
    )
    .unwrap_or_else(|e: Error| panic!("{} build_clean_background_pdf: {e}", case.name));

    assert_eq!(
        outcome.per_page_diagnostics.len(),
        case.per_page_diagnostics.len(),
        "{}: per-page diagnostics length",
        case.name
    );
    for (i, (actual, expected)) in outcome
        .per_page_diagnostics
        .iter()
        .zip(case.per_page_diagnostics.iter())
        .enumerate()
    {
        match (actual, expected) {
            (Some(a), Some(e)) => assert_diag_eq(a, e, &format!("{} p{i}", case.name)),
            (None, None) => {}
            (Some(_), None) => panic!("{} p{i}: expected skipped, got diagnostics", case.name),
            (None, Some(_)) => panic!("{} p{i}: expected diagnostics, got skip", case.name),
        }
    }

    assert_eq!(
        outcome.toc_entries, case.toc_entries,
        "{}: toc_entries",
        case.name
    );

    delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
    let out_path = dir.join("out.pdf");
    save_optimized(&pdf, &out_path).unwrap_or_else(|e| panic!("{} save_optimized: {e}", case.name));
    let out_doc = Document::open(out_path.as_path())
        .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
    let output_facts = measure_pages(&out_doc, page_count, scale, threshold);
    assert_page_facts(&output_facts, &case.expected_output.pages, &format!("{} output", case.name));

    let outlines = out_doc.outlines().unwrap_or_else(|e| panic!("{} outlines: {e}", case.name));
    let mut flat: Vec<StageTocEntry> = Vec::new();
    flatten_outlines(&outlines, 1, &mut flat);
    assert_eq!(
        flat.len(),
        case.toc.len(),
        "{}: output outline count actual={flat:?} expected={:?}",
        case.name,
        case.toc
    );
    for (actual, expected) in flat.iter().zip(case.toc.iter()) {
        assert_eq!(actual.level, expected.level, "{}: toc level", case.name);
        assert_eq!(actual.title, expected.title, "{}: toc title", case.name);
        assert_eq!(actual.page, expected.page, "{}: toc page", case.name);
    }
}

#[test]
fn stage_replay_matches_production() {
    let corpus = stage_corpus();
    assert_eq!(corpus.schema, "retainpdf_stage_corpus_v1");
    assert!(!corpus.cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;
    for case in &corpus.cases {
        replay_case(case, scale, threshold);
    }
}
