//! Phase 7R-6 vector-text differential: mupdf-rs `background::vector_text` vs
//! production `source/vector_text.py::collect_vector_text_rects`.
//!
//! Replays `tests/vector_text_corpus.json` (generated by
//! `differential/gen_vector_text_corpus.py`, which runs the REAL production
//! classifier and asserts each case before recording). For each case the Rust
//! side opens a `Document` from the corpus bytes, runs
//! `collect_vector_text_rects` with the target rects, and asserts the returned
//! rects match `expected_rects` within the corpus's 0.02 pt tolerance.

use std::fs;
use std::path::Path;

use mupdf::Document;
use rendering_core::source_cleanup::hit_test::RectTuple;
use rendering_writer::background::vector_text::collect_vector_text_rects;

mod common;
use common::{decode, vector_text_corpus, VectorTextCase};

const TOLERANCE: f64 = 0.02;

fn write_input(dir: &Path, name: &str, bytes: &[u8]) -> std::path::PathBuf {
    let path = dir.join(name);
    fs::write(&path, bytes).expect("write input pdf");
    path
}

fn assert_rect_eq(actual: &RectTuple, expected: &[f64], label: &str) {
    assert_eq!(actual.len(), expected.len(), "{label}: rect dim");
    for i in 0..actual.len() {
        let diff = (actual[i] - expected[i]).abs();
        assert!(
            diff <= TOLERANCE,
            "{label}[{i}]: actual={:?} expected={expected:?} diff={diff:.4} > {TOLERANCE}",
            actual
        );
    }
}

fn replay_case(case: &VectorTextCase) {
    let dir = std::env::temp_dir().join(format!("rpvt-{}-{}", case.name, std::process::id()));
    fs::create_dir_all(&dir).expect("create temp dir");
    let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));

    let doc = Document::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} doc open: {e}", case.name));

    let targets: Vec<RectTuple> = case
        .target_rects
        .iter()
        .map(|r| [r[0], r[1], r[2], r[3]])
        .collect();

    let got = collect_vector_text_rects(&doc, 0, &targets);
    assert_eq!(
        got.len(),
        case.expected_rects.len(),
        "{}: rect count got={got:?} expected={:?}",
        case.name,
        case.expected_rects
    );
    for (actual, expected) in got.iter().zip(case.expected_rects.iter()) {
        assert_rect_eq(actual, expected, &format!("{}", case.name));
    }
}

#[test]
fn vector_text_replay_matches_production() {
    let corpus = vector_text_corpus();
    assert_eq!(corpus.schema, "retainpdf_vector_text_corpus_v1");
    assert!(!corpus.cases.is_empty());
    for case in &corpus.cases {
        replay_case(case);
    }
}
