//! Phase 5C write differential: mupdf-rs strip write path vs production.
//!
//! Replays `tests/write_corpus.json` (generated by
//! `differential/gen_write_corpus.py`, which runs the REAL pikepdf pipeline and
//! records strip-result counts plus per-page words/ink_ratio for input and
//! output). For each case:
//!   1. decode the embedded input PDF and open it with mupdf-rs,
//!   2. run `strip_bbox_text_rects_from_pdf` with the recorded rects,
//!   3. assert the strip result counts match exactly,
//!   4. save (deterministic: trailer /ID deleted) and reopen,
//!   5. measure per-page words + ink_ratio on input and output and compare vs
//!      the fitz-computed corpus facts (word count within 10% rel, ink within
//!      ±0.02 abs).

use std::collections::HashMap;
use std::fs;
use std::path::Path;

use mupdf::Document;
use rendering_core::source_cleanup::hit_test::RectTuple;
use rendering_writer::cleanup_writer::strip_bbox_text_rects_from_pdf;
use rendering_writer::hidden_text::strip_hidden_text;
use rendering_writer::image_compress::compress_images;
use rendering_writer::overlay::overlay_page;
use rendering_writer::page_subset::extract_pages;
use rendering_writer::sanitize::{count_invalid_images, sanitize_invalid_xobjects, xobject_subtypes};
use rendering_writer::save::{delete_trailer_id, save_atomic, save_optimized};

mod common;
use common::{
    assert_page_facts, corpus, decode, measure_pages, rect_map, HiddenTextCase, PrepCase,
    SanitizeCase, WriteCase,
};

/// Relative size tolerance vs the fitz reference save. Native does no font
/// subsetting (production subsets in fitz first) and no object streams, so it
/// can be slightly larger; measured ratios on the corpus are 1.001-1.079
/// (fitz `use_objstms=1` compresses the subset font's object structure better
/// than mupdf-rs's flat object graph), so 1.15 leaves margin while still
/// catching a compaction regression (native growing >15%).
const SAVE_SIZE_K: f64 = 1.15;

fn build_page_rects(case: &WriteCase) -> HashMap<i32, Vec<RectTuple>> {
    rect_map(&case.page_rects)
}

fn build_protected(case: &WriteCase) -> HashMap<i32, Vec<RectTuple>> {
    rect_map(&case.page_protected_rects)
}

/// Write `bytes` to a fresh temp file inside `dir` and return its path.
fn write_input(dir: &Path, name: &str, bytes: &[u8]) -> std::path::PathBuf {
    let path = dir.join(name);
    fs::write(&path, bytes).expect("write input pdf");
    path
}

#[test]
fn strip_replay_matches_production() {
    let corpus = corpus();
    assert_eq!(corpus.schema, "retainpdf_write_corpus_v1");
    assert!(!corpus.cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;

    for case in &corpus.cases {
        let dir = tempfile_dir(&case.name);
        let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));

        // Open the input once for pre-strip measurement, once for stripping
        // (the strip mutates the PdfDocument in place).
        let input_meas = Document::open(in_path.as_path()).unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
        let input_facts = measure_pages(&input_meas, case.page_count, scale, threshold);
        assert_page_facts(&input_facts, &case.expected.input.pages, &format!("{} input", case.name));

        let mut pdf = mupdf::pdf::PdfDocument::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open for strip: {e}", case.name));
        let page_rects = build_page_rects(case);
        let protected = build_protected(case);
        let result = strip_bbox_text_rects_from_pdf(
            &mut pdf,
            &page_rects,
            &protected,
            case.recurse_forms,
        )
        .unwrap_or_else(|e| panic!("{} strip: {e}", case.name));

        assert_eq!(
            result.pages_changed,
            case.expected.pages_changed,
            "{} pages_changed",
            case.name
        );
        assert_eq!(
            result.text_show_ops_removed,
            case.expected.text_show_ops_removed,
            "{} text_show_ops_removed",
            case.name
        );
        assert_eq!(
            result.forms_changed,
            case.expected.forms_changed,
            "{} forms_changed",
            case.name
        );
        assert_eq!(
            result.changed_page_indices,
            case.expected.changed_page_indices,
            "{} changed_page_indices",
            case.name
        );

        delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
        let out_path = dir.join("out.pdf");
        save_atomic(&pdf, &out_path).unwrap_or_else(|e| panic!("{} save: {e}", case.name));

        let out_doc = Document::open(out_path.as_path())
            .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
        assert_eq!(
            out_doc.page_count().unwrap_or(0) as usize,
            case.page_count,
            "{} output page_count",
            case.name
        );
        let output_facts = measure_pages(&out_doc, case.page_count, scale, threshold);
        assert_page_facts(
            &output_facts,
            &case.expected.output.pages,
            &format!("{} output", case.name),
        );
    }
}

#[test]
fn save_replay_matches_production() {
    let corpus = corpus();
    assert!(!corpus.save_cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;

    for case in &corpus.save_cases {
        let dir = tempfile_dir(&format!("save-{}", case.name));
        let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));

        let input_doc = Document::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
        let input_facts = measure_pages(
            &input_doc,
            input_doc.page_count().unwrap_or(0) as usize,
            scale,
            threshold,
        );
        assert_page_facts(
            &input_facts,
            &case.expected.input.pages,
            &format!("{} input", case.name),
        );

        let pdf = mupdf::pdf::PdfDocument::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open for save: {e}", case.name));
        delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
        let out_path = dir.join("out.pdf");
        save_optimized(&pdf, &out_path)
            .unwrap_or_else(|e| panic!("{} save_optimized: {e}", case.name));
        let out_bytes = fs::read(&out_path).expect("read output");
        assert!(
            out_bytes.starts_with(b"%PDF-"),
            "{} output is not a valid PDF (bad header)",
            case.name,
        );

        let out_doc = Document::open(out_path.as_path())
            .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
        let out_pages = out_doc.page_count().unwrap_or(0) as usize;
        assert_eq!(
            out_pages,
            case.expected.output_page_count,
            "{} output_page_count",
            case.name
        );
        let output_facts = measure_pages(&out_doc, out_pages, scale, threshold);
        assert_page_facts(
            &output_facts,
            &case.expected.output.pages,
            &format!("{} output", case.name),
        );

        let size_ratio = out_bytes.len() as f64 / case.expected.output_bytes as f64;
        assert!(
            size_ratio <= SAVE_SIZE_K,
            "{} native output {}/{} = {:.3} > k={SAVE_SIZE_K}",
            case.name,
            out_bytes.len(),
            case.expected.output_bytes,
            size_ratio,
        );
    }
}

#[test]
fn subset_replay_matches_production() {
    let corpus = corpus();
    assert!(!corpus.subset_cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;

    for case in &corpus.subset_cases {
        let dir = tempfile_dir(&format!("subset-{}", case.name));
        let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));

        let input_doc = Document::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
        let input_facts = measure_pages(
            &input_doc,
            input_doc.page_count().unwrap_or(0) as usize,
            scale,
            threshold,
        );
        assert_page_facts(
            &input_facts,
            &case.expected.input.pages,
            &format!("{} input", case.name),
        );

        let mut pdf = mupdf::pdf::PdfDocument::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open for subset: {e}", case.name));
        let out = extract_pages(&mut pdf, case.start_page, case.end_page)
            .unwrap_or_else(|e| panic!("{} extract: {e}", case.name));
        let out_pages = out.page_count().unwrap_or(0) as usize;
        assert_eq!(
            out_pages,
            case.expected.output_page_count,
            "{} output_page_count",
            case.name
        );
        let output_facts = measure_pages(&*out, out_pages, scale, threshold);
        assert_page_facts(
            &output_facts,
            &case.expected.output.pages,
            &format!("{} output", case.name),
        );
    }
}

#[test]
fn overlay_replay_matches_production() {
    let corpus = corpus();
    assert!(!corpus.overlay_cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;

    for case in &corpus.overlay_cases {
        let dir = tempfile_dir(&format!("overlay-{}", case.name));
        let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));
        let ovl_path = write_input(&dir, "ovl.pdf", &decode(&case.overlay_pdf_b64));

        let input_doc = Document::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
        let input_facts = measure_pages(
            &input_doc,
            input_doc.page_count().unwrap_or(0) as usize,
            scale,
            threshold,
        );
        assert_page_facts(
            &input_facts,
            &case.expected.input.pages,
            &format!("{} input", case.name),
        );

        let mut source = mupdf::pdf::PdfDocument::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open source: {e}", case.name));
        let overlay = mupdf::pdf::PdfDocument::open(ovl_path.as_path())
            .unwrap_or_else(|e| panic!("{} open overlay: {e}", case.name));
        overlay_page(&mut source, 0, &overlay, 0)
            .unwrap_or_else(|e| panic!("{} overlay: {e}", case.name));

        delete_trailer_id(&source).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
        let out_path = dir.join("out.pdf");
        save_atomic(&source, &out_path).unwrap_or_else(|e| panic!("{} save: {e}", case.name));

        let out_doc = Document::open(out_path.as_path())
            .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
        assert_eq!(
            out_doc.page_count().unwrap_or(0),
            1,
            "{} output page_count",
            case.name
        );
        let output_facts = measure_pages(&out_doc, 1, scale, threshold);
        assert_page_facts(
            &output_facts,
            &case.expected.output.pages,
            &format!("{} output", case.name),
        );
    }
}

#[test]
fn image_replay_matches_production() {
    let corpus = corpus();
    assert!(!corpus.image_cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;

    for case in &corpus.image_cases {
        let dir = tempfile_dir(&format!("image-{}", case.name));
        let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));
        let in_bytes = fs::read(&in_path).expect("read input");

        let input_doc = Document::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
        let input_facts = measure_pages(
            &input_doc,
            input_doc.page_count().unwrap_or(0) as usize,
            scale,
            threshold,
        );
        assert_page_facts(
            &input_facts,
            &case.expected.input.pages,
            &format!("{} input", case.name),
        );

        // The corpus case has exactly one displayed image; record its facts
        // before compression to prove the recompressed output shrank.
        let mut pdf = mupdf::pdf::PdfDocument::open(in_path.as_path())
            .unwrap_or_else(|e| panic!("{} open for compress: {e}", case.name));
        let input_page = pdf.load_pdf_page(0).unwrap_or_else(|e| panic!("{} input p0: {e}", case.name));
        let input_images = input_page.images().unwrap_or_else(|e| panic!("{} input images: {e}", case.name));
        assert_eq!(input_images.len(), 1, "{} input image count", case.name);
        let input_xref = input_images[0].xref;
        let input_extracted = pdf.extract_image(input_xref)
            .unwrap_or_else(|e| panic!("{} extract input: {e}", case.name));
        assert_eq!(input_extracted.width as i64, case.expected.input_image.width, "{} input width", case.name);
        assert_eq!(input_extracted.height as i64, case.expected.input_image.height, "{} input height", case.name);
        assert_eq!(input_extracted.encoded.len(), case.expected.input_image.encoded_len, "{} input encoded_len", case.name);

        let result = compress_images(&mut pdf, case.dpi)
            .unwrap_or_else(|e| panic!("{} compress: {e}", case.name));
        assert_eq!(result.changed, case.expected.changed, "{} changed", case.name);
        assert_eq!(result.recompressed_xrefs.len(), 1, "{} recompressed count", case.name);

        delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
        let out_path = dir.join("out.pdf");
        save_atomic(&pdf, &out_path).unwrap_or_else(|e| panic!("{} save: {e}", case.name));
        let out_bytes = fs::read(&out_path).expect("read output");
        assert!(
            out_bytes.len() < in_bytes.len(),
            "{} output file not smaller: {} >= {}",
            case.name,
            out_bytes.len(),
            in_bytes.len(),
        );

        let out_doc = Document::open(out_path.as_path())
            .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
        assert_eq!(out_doc.page_count().unwrap_or(0), 1, "{} output page_count", case.name);
        let output_facts = measure_pages(&out_doc, 1, scale, threshold);
        assert_page_facts(
            &output_facts,
            &case.expected.output.pages,
            &format!("{} output", case.name),
        );

        // Structural: the output image is resized to the display target and
        // re-encoded as DCTDecode strictly smaller than the original image.
        let out_pdf = mupdf::pdf::PdfDocument::open(out_path.as_path())
            .unwrap_or_else(|e| panic!("{} reopen pdf: {e}", case.name));
        let out_page = out_pdf.load_pdf_page(0).unwrap_or_else(|e| panic!("{} output p0: {e}", case.name));
        let out_images = out_page.images().unwrap_or_else(|e| panic!("{} output images: {e}", case.name));
        assert_eq!(out_images.len(), 1, "{} output image count", case.name);
        let out_extracted = out_pdf.extract_image(out_images[0].xref)
            .unwrap_or_else(|e| panic!("{} extract output: {e}", case.name));
        assert_eq!(out_extracted.width as i64, case.expected.output_image.width, "{} output width", case.name);
        assert_eq!(out_extracted.height as i64, case.expected.output_image.height, "{} output height", case.name);
        assert!(
            out_extracted.encoded.len() < case.expected.input_image.encoded_len,
            "{} output image not smaller: {} >= {}",
            case.name,
            out_extracted.encoded.len(),
            case.expected.input_image.encoded_len,
        );
        let out_filter = out_extracted.filter.as_deref().unwrap_or("");
        assert!(
            out_filter.contains("DCTDecode"),
            "{} output filter not DCTDecode: {out_filter}",
            case.name,
        );
    }
}

#[test]
fn prep_replay_matches_production() {
    let corpus = corpus();
    assert!(!corpus.prep_cases.is_empty());
    let scale = corpus.render_scale as f32;
    let threshold = corpus.ink_threshold;

    for case in &corpus.prep_cases {
        match case {
            PrepCase::Hidden(c) => replay_hidden(c, scale, threshold),
            PrepCase::Sanitize(c) => replay_sanitize(c, scale, threshold),
        }
    }
}

fn replay_hidden(case: &HiddenTextCase, scale: f32, threshold: u8) {
    let dir = tempfile_dir(&format!("hidden-{}", case.name));
    let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));
    let page_count = case.expected.input.pages.len();

    let input_meas = Document::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
    let input_facts = measure_pages(&input_meas, page_count, scale, threshold);
    assert_page_facts(
        &input_facts,
        &case.expected.input.pages,
        &format!("{} input", case.name),
    );

    let mut pdf = mupdf::pdf::PdfDocument::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open for strip: {e}", case.name));
    let result = strip_hidden_text(&mut pdf)
        .unwrap_or_else(|e| panic!("{} hidden_text strip: {e}", case.name));
    assert_eq!(
        result.pages_changed,
        case.expected.pages_changed,
        "{} pages_changed",
        case.name
    );
    assert_eq!(
        result.text_objects_removed,
        case.expected.text_objects_removed,
        "{} text_objects_removed",
        case.name
    );

    delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
    let out_path = dir.join("out.pdf");
    save_atomic(&pdf, &out_path).unwrap_or_else(|e| panic!("{} save: {e}", case.name));

    let out_doc = Document::open(out_path.as_path())
        .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
    assert_eq!(
        out_doc.page_count().unwrap_or(0) as usize,
        page_count,
        "{} output page_count",
        case.name
    );
    let output_facts = measure_pages(&out_doc, page_count, scale, threshold);
    assert_page_facts(
        &output_facts,
        &case.expected.output.pages,
        &format!("{} output", case.name),
    );
}

fn replay_sanitize(case: &SanitizeCase, scale: f32, threshold: u8) {
    let dir = tempfile_dir(&format!("sanitize-{}", case.name));
    let in_path = write_input(&dir, "in.pdf", &decode(&case.input_pdf_b64));
    let page_count = case.expected.input.pages.len();

    let input_meas = Document::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open input: {e}", case.name));
    let input_facts = measure_pages(&input_meas, page_count, scale, threshold);
    assert_page_facts(
        &input_facts,
        &case.expected.input.pages,
        &format!("{} input", case.name),
    );

    let mut pdf = mupdf::pdf::PdfDocument::open(in_path.as_path())
        .unwrap_or_else(|e| panic!("{} open for sanitize: {e}", case.name));
    let result = sanitize_invalid_xobjects(&mut pdf)
        .unwrap_or_else(|e| panic!("{} sanitize: {e}", case.name));
    assert_eq!(
        result.invalid_image_xobjects,
        case.expected.invalid_image_xobjects,
        "{} invalid_image_xobjects",
        case.name
    );
    assert_eq!(
        result.pages_changed,
        case.expected.pages_changed,
        "{} pages_changed",
        case.name
    );

    delete_trailer_id(&pdf).unwrap_or_else(|e| panic!("{} delete_trailer_id: {e}", case.name));
    let out_path = dir.join("out.pdf");
    save_atomic(&pdf, &out_path).unwrap_or_else(|e| panic!("{} save: {e}", case.name));

    let out_doc = Document::open(out_path.as_path())
        .unwrap_or_else(|e| panic!("{} reopen output: {e}", case.name));
    assert_eq!(
        out_doc.page_count().unwrap_or(0) as usize,
        page_count,
        "{} output page_count",
        case.name
    );
    let output_facts = measure_pages(&out_doc, page_count, scale, threshold);
    assert_page_facts(
        &output_facts,
        &case.expected.output.pages,
        &format!("{} output", case.name),
    );

    // Structural: the output resource tree holds exactly the recorded image
    // counts (the invalid image replaced, the valid one retained).
    let out_pdf = mupdf::pdf::PdfDocument::open(out_path.as_path())
        .unwrap_or_else(|e| panic!("{} reopen pdf: {e}", case.name));
    let (total, invalid) = count_invalid_images(&out_pdf)
        .unwrap_or_else(|e| panic!("{} count_invalid_images: {e}", case.name));
    assert_eq!(
        total,
        case.expected.output_image_count,
        "{} output_image_count",
        case.name
    );
    assert_eq!(
        invalid,
        case.expected.output_invalid_image_count,
        "{} output_invalid_image_count",
        case.name
    );
    let subtypes = xobject_subtypes(&out_pdf)
        .unwrap_or_else(|e| panic!("{} xobject_subtypes: {e}", case.name));
    let expected_subtypes: Vec<(String, String)> = case
        .expected
        .output_xobject_subtypes
        .iter()
        .map(|pair| (pair[0].clone(), pair[1].clone()))
        .collect();
    assert_eq!(
        subtypes, expected_subtypes,
        "{} output_xobject_subtypes",
        case.name
    );
}

/// Unique temp dir per case (scoped to the OS temp dir; cleaned by the OS).
fn tempfile_dir(name: &str) -> std::path::PathBuf {
    let base = std::env::temp_dir().join(format!(
        "rpsave-{}-{}",
        name,
        std::process::id()
    ));
    fs::create_dir_all(&base).expect("create temp dir");
    base
}
