[package]
name = "rendering_bridge"
version = "0.1.0"
edition = "2021"

[lib]
name = "rendering_bridge"
crate-type = ["cdylib"]

[build-dependencies]
pyo3-build-config = { version = "0.29" }

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mupdf = { version = "0.8", default-features = false, features = ["base14-fonts"] }
rendering_core = { path = "../rendering_core" }
rendering_output = { path = "../rendering_output" }
rendering_reader = { path = "../rendering_reader" }
rendering_writer = { path = "../rendering_writer" }
